# Generated by Django 5.2.17 on 2026-09-25 20:16

import django.db.models.deletion
import pme360.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_rls'),
        ('pmes', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PmeObligation',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('PONCTUELLE', 'Ponctuelle'), ('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle'), ('SEMESTRIELLE', 'Semestrielle'), ('ANNUELLE', 'Annuelle')], max_length=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('DISPENSEE', 'Dispensée')], default='ACTIVE', max_length=10)),
                ('waiver_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'pme_obligation',
            },
        ),
        migrations.CreateModel(
            name='RegulatoryRule',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(help_text='Ce qui a été identifié (et ce qui reste à confirmer).')),
                ('authority', models.CharField(max_length=60)),
                ('sources', models.JSONField(default=list, help_text='[{title, url}] — sources officielles puis secondaires.')),
                ('source_reference', models.CharField(blank=True, help_text='Texte et article précis.', max_length=250)),
                ('status', models.CharField(choices=[('A_VERIFIER', 'À vérifier'), ('PRE_VERIFIE', 'Pré-vérifiée (source identifiée)'), ('VERIFIE', 'Vérifiée'), ('OBSOLETE', 'Obsolète'), ('HORS_PERIMETRE', 'Hors périmètre')], default='A_VERIFIER', max_length=16)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('verification_note', models.TextField(blank=True)),
                ('review_due_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'regulatory_rule',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('A_FOURNIR', 'À fournir'), ('EN_ATTENTE', 'En attente'), ('RECU', 'Reçu'), ('EN_ANALYSE', 'En analyse'), ('VERIF_HUMAINE_REQUISE', 'Vérification humaine requise'), ('CONFORME', 'Conforme'), ('CONFORME_SOUS_RESERVE', 'Conforme sous réserve'), ('NON_CONFORME', 'Non conforme'), ('EXPIRE', 'Document expiré'), ('INCOHERENT', 'Document incohérent'), ('EN_RETARD', 'En retard'), ('DISPENSE', 'Dispensée')], default='A_FOURNIR', max_length=22)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='pmes.pme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deadline',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineReminder',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offset_days', models.IntegerField()),
                ('sent_on', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='compliance.deadline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deadline_reminder',
            },
        ),
        migrations.CreateModel(
            name='ObligationTemplate',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('nature', models.CharField(choices=[('REGLEMENTAIRE', 'Réglementaire'), ('PROGRAMME', 'Programme (transmission à GUDE-PME)'), ('BONNE_PRATIQUE', 'Bonne pratique')], max_length=16)),
                ('frequency', models.CharField(choices=[('PONCTUELLE', 'Ponctuelle'), ('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle'), ('SEMESTRIELLE', 'Semestrielle'), ('ANNUELLE', 'Annuelle')], max_length=14)),
                ('frequency_rule', models.JSONField(blank=True, null=True)),
                ('due_days_after_period_end', models.PositiveIntegerField(default=30)),
                ('applicability', models.JSONField(blank=True, help_text='JSON Logic sur le profil de la PME.', null=True)),
                ('reminder_offsets', models.JSONField(default=list, help_text="Jours relatifs à l'échéance, ex. [-30,-15,-7,0,7,15,30].")),
                ('is_critical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'obligation_template',
                'ordering': ['code'],
            },
        ),
    ]
