# Generated by Django 5.2.17 on 2026-09-25 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('documents', '0001_initial'),
        ('organizations', '0002_rls'),
        ('pmes', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obligationtemplate',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.documenttype'),
        ),
        migrations.AddField(
            model_name='obligationtemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='obligationtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmeobligation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmeobligation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='pmeobligation',
            name='pme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='pmes.pme'),
        ),
        migrations.AddField(
            model_name='pmeobligation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pme_obligations', to='compliance.obligationtemplate'),
        ),
        migrations.AddField(
            model_name='pmeobligation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deadline',
            name='pme_obligation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='compliance.pmeobligation'),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obligationtemplate',
            name='regulatory_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='compliance.regulatoryrule'),
        ),
        migrations.AddConstraint(
            model_name='deadlinereminder',
            constraint=models.UniqueConstraint(fields=('deadline', 'offset_days'), name='deadline_reminder_unique'),
        ),
        migrations.AddConstraint(
            model_name='pmeobligation',
            constraint=models.UniqueConstraint(fields=('pme', 'template'), name='pme_obligation_unique'),
        ),
        migrations.AddIndex(
            model_name='deadline',
            index=models.Index(fields=['organization', 'due_date', 'status'], name='deadline_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='deadline',
            constraint=models.UniqueConstraint(fields=('pme_obligation', 'period_start'), name='deadline_unique_period'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryrule',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='regulatory_rule_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'VERIFIE'), _negated=True), models.Q(('verified_at__isnull', False), ('verified_by__isnull', False), models.Q(('source_reference', ''), _negated=True)), _connector='OR'), name='regulatory_rule_verified_is_documented'),
        ),
        migrations.AddConstraint(
            model_name='obligationtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='obligation_template_unique_code'),
        ),
    ]
