# Generated by Django 5.2.17 on 2026-09-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligationtemplate',
            name='nature',
            field=models.CharField(choices=[('REGLEMENTAIRE', 'Réglementaire'), ('PROGRAMME', "Programme (transmission à l'organisation)"), ('BONNE_PRATIQUE', 'Bonne pratique')], max_length=16),
        ),
    ]
