# Generated by Django 5.2.17 on 2026-09-25 20:16

import django.db.models.deletion
import pme360.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_rls'),
        ('pmes', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('kind', models.CharField(help_text="Type d'alerte évalué par le moteur.", max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Élevée'), ('CRITIQUE', 'Critique')], max_length=10)),
                ('params', models.JSONField(default=dict, help_text='Seuils de la règle (jours, points, pourcentages…).')),
                ('recipients', models.JSONField(default=list, help_text='Destinataires : PME, CONSEILLER, RESPONSABLE_PROGRAMME, EXPERT.')),
                ('is_active', models.BooleanField(default=True)),
                ('available_in_phase', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_rule',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('MOYENNE', 'Moyenne'), ('ELEVEE', 'Élevée'), ('CRITIQUE', 'Critique')], max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('dedup_key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('RESOLUE', 'Résolue'), ('IGNOREE', 'Ignorée')], default='OUVERTE', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='pmes.pme')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'db_table': 'alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='alert_rule_unique_code'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'status', 'severity'], name='alert_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OUVERTE', 'PRISE_EN_COMPTE'])), fields=('rule', 'dedup_key'), name='alert_one_open_per_key'),
        ),
    ]
