# Generated by Django 5.2.17 on 2026-09-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_action_comment_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='owner_type',
            field=models.CharField(choices=[('PME', 'PME'), ('GUDE', "L'organisation d'accompagnement"), ('PARTENAIRE', 'Partenaire')], default='PME', max_length=10),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('BLOQUE', 'Bloquée (dépendance)'), ('NON_COMMENCE', 'Non commencée'), ('EN_COURS', 'En cours'), ('DOCUMENT_DEMANDE', 'Document demandé'), ('DOCUMENT_RECU', 'Document reçu'), ('A_VERIFIER', 'À vérifier'), ('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('TERMINE', 'Terminée'), ('EN_ATTENTE_PME', 'En attente de la PME'), ('EN_ATTENTE_GUDE', "En attente de l'organisation"), ('ABANDONNE', 'Abandonnée')], default='NON_COMMENCE', max_length=16),
        ),
        migrations.AlterField(
            model_name='comment',
            name='visibility',
            field=models.CharField(choices=[('INTERNE_GUDE', "Interne à l'équipe"), ('PARTAGE_PME', 'Partagé avec la PME')], max_length=14),
        ),
        migrations.AlterField(
            model_name='supportoffer',
            name='provider_type',
            field=models.CharField(choices=[('GUDE', "L'organisation d'accompagnement"), ('PARTENAIRE', 'Partenaire'), ('PME_SEULE', 'PME en autonomie')], default='GUDE', max_length=12),
        ),
    ]
