# Generated by Django 5.2.17 on 2026-09-25 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'Utilisateur'), ('SYSTEM', 'Système'), ('AI', 'IA')], max_length=10)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=60)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('pme_id', models.UUIDField(blank=True, null=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('at', models.DateTimeField()),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['organization', 'entity_type', 'entity_id'], name='audit_entity_idx'), models.Index(fields=['organization', 'pme_id', 'at'], name='audit_pme_idx'), models.Index(fields=['organization', 'actor', 'at'], name='audit_actor_idx')],
            },
        ),
    ]
