# Generated by Django 5.2.17 on 2026-09-25 22:15

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pme360.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostic', '0002_security'),
        ('documents', '0002_rls'),
        ('organizations', '0002_rls'),
        ('pmes', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysis',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.CharField(choices=[('CLASSIFICATION', 'Classification documentaire'), ('EXTRACTION', 'Extraction structurée'), ('CONTROLE', 'Contrôles et anomalies'), ('ANALYSE_FINANCIERE', 'Interprétation financière'), ('PRE_DIAGNOSTIC', 'Pré-diagnostic'), ('ASK_AI', 'Ask AI')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCES', 'Succès'), ('SORTIE_INVALIDE', 'Sortie invalide (vérification humaine)'), ('REFUSE_POLITIQUE', 'Refusé par la politique du tenant'), ('BUDGET_EPUISE', 'Budget épuisé'), ('DIFFERE', 'Fournisseur indisponible : analyse différée'), ('ECHEC', 'Échec')], max_length=16)),
                ('provider', models.CharField(help_text='local (règles, sans envoi externe) | anthropic', max_length=20)),
                ('model', models.CharField(help_text='Identifiant exact du modèle (ou du moteur de règles).', max_length=60)),
                ('prompt_code', models.CharField(max_length=60)),
                ('prompt_version', models.CharField(max_length=20)),
                ('input_refs', models.JSONField(default=dict, help_text='Documents, versions, réponses et fragments utilisés.')),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('pseudonymized', models.BooleanField(default=False)),
                ('output', models.JSONField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_analyses', to='diagnostic.diagnostic')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_analyses', to='documents.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pmes.pme')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pmes.pme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('confidence', models.CharField(blank=True, max_length=10)),
                ('limits', models.JSONField(default=list)),
                ('tool_calls', models.JSONField(default=list)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.aianalysis')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversation_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CriterionSuggestion',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criterion_code', models.CharField(max_length=40)),
                ('proposed_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('justification', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('status', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('ACCEPTEE', 'Acceptée'), ('MODIFIEE', 'Modifiée par le conseiller'), ('ECARTEE', 'Écartée')], default='PROPOSEE', max_length=10)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.aianalysis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='diagnostic.diagnostic')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'criterion_suggestion',
            },
        ),
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_type', models.CharField(max_length=40)),
                ('classified_type', models.CharField(blank=True, max_length=40)),
                ('classification_confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('schema_code', models.CharField(blank=True, max_length=40)),
                ('schema_version', models.CharField(blank=True, max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('field_confidence', models.JSONField(default=dict)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('PROVISOIRE', 'Provisoire (confiance suffisante)'), ('A_VERIFIER', 'À vérifier'), ('VALIDEE', 'Validée'), ('CORRIGEE', 'Corrigée'), ('REJETEE', 'Rejetée'), ('NON_ANALYSEE', 'Non analysée')], default='NON_ANALYSEE', max_length=14)),
                ('reason', models.CharField(blank=True, help_text='Pourquoi une vérification humaine est requise.', max_length=300)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('corrections', models.JSONField(default=dict, help_text='{champ: {before, after}} (human_review).')),
                ('review_comment', models.TextField(blank=True)),
                ('classification_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.aianalysis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('extraction_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.aianalysis')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='documents.documentversion')),
            ],
            options={
                'db_table': 'document_extraction',
            },
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.CharField(max_length=60)),
                ('provider', models.CharField(max_length=20)),
                ('models_used', models.JSONField(default=dict)),
                ('prompt_versions', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('thresholds', models.JSONField(default=dict)),
                ('passed', models.BooleanField()),
                ('details', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_evaluation_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year_end', models.DateField()),
                ('system', models.CharField(blank=True, help_text='NORMAL | SMT | INCONNU', max_length=10)),
                ('values', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PROVISOIRE', 'Provisoire (extraction IA)'), ('VERIFIE', 'Vérifié'), ('ECARTE', 'Écarté')], max_length=10)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_statements', to='pmes.pme')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_statements', to='documents.documentversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_statement',
                'ordering': ['-fiscal_year_end'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('REFERENTIEL', 'Référentiel de diagnostic'), ('REGLEMENTATION', 'Registre réglementaire (vérifié)'), ('DOCUMENT', 'Document de la PME'), ('HISTORIQUE', 'Historique de la PME')], max_length=16)),
                ('source_id', models.CharField(max_length=64)),
                ('source_label', models.CharField(max_length=300)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pmes.pme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_chunk',
            },
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['organization', 'created_at'], name='ai_analysis_org_date_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['organization', 'pme', 'task'], name='ai_analysis_pme_task_idx'),
        ),
        migrations.AddConstraint(
            model_name='criterionsuggestion',
            constraint=models.UniqueConstraint(fields=('diagnostic', 'criterion_code'), name='criterion_suggestion_unique'),
        ),
        migrations.AddConstraint(
            model_name='criterionsuggestion',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_level__isnull', True), ('proposed_level__lte', 4), _connector='OR'), name='suggestion_level_range'),
        ),
        migrations.AddConstraint(
            model_name='financialstatement',
            constraint=models.UniqueConstraint(fields=('pme', 'fiscal_year_end'), name='financial_statement_unique_year'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='knowledge_chunk_search_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['organization', 'source_type', 'source_id'], name='knowledge_chunk_source_idx'),
        ),
    ]
