# Generated by Django 5.2.17 on 2026-09-25 17:19

import django.db.models.deletion
import pme360.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostic', '0001_initial'),
        ('organizations', '0002_rls'),
        ('pmes', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('BASELINE', 'Référence (diagnostic initial)'), ('FOLLOW_UP', 'Suivi'), ('CLOTURE', 'Clôture'), ('LIVE', 'Score courant')], max_length=10)),
                ('reference_date', models.DateField()),
                ('computed_at', models.DateTimeField()),
                ('engine_version', models.CharField(max_length=20)),
                ('global_score', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('imo', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='indice de maturité organisationnelle')),
                ('ipe', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='indice de performance économique')),
                ('risk_index', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('digital_index', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('maturity_level', models.PositiveSmallIntegerField(null=True)),
                ('maturity_level_uncapped', models.PositiveSmallIntegerField(null=True)),
                ('gates_failed', models.JSONField(default=list)),
                ('intervention_priority', models.CharField(blank=True, max_length=2)),
                ('quadrant', models.CharField(blank=True, max_length=30)),
                ('is_frozen', models.BooleanField(default=True)),
                ('result', models.JSONField(default=dict, help_text='Résultat complet du moteur (explicabilité).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diagnostic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='diagnostic.diagnostic')),
                ('framework_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='diagnostic.frameworkversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='pmes.pme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'score_snapshot',
                'ordering': ['-reference_date', '-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreItem',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('PILLAR', 'Pilier'), ('DIMENSION', 'Dimension'), ('CRITERION', 'Critère'), ('LENS', 'Lentille')], max_length=10)),
                ('ref_code', models.CharField(max_length=40)),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('status', models.CharField(max_length=16)),
                ('details', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scoring.scoresnapshot')),
            ],
            options={
                'db_table': 'score_item',
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_code', models.CharField(max_length=40)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('points', models.PositiveSmallIntegerField(null=True)),
                ('band_label', models.CharField(blank=True, max_length=60)),
                ('inputs_used', models.JSONField(default=dict)),
                ('sources', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='scoring.scoresnapshot')),
            ],
            options={
                'db_table': 'metric_value',
            },
        ),
        migrations.AddIndex(
            model_name='scoresnapshot',
            index=models.Index(fields=['organization', 'pme', 'reference_date'], name='snapshot_pme_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoreitem',
            constraint=models.UniqueConstraint(fields=('snapshot', 'scope', 'ref_code'), name='score_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.UniqueConstraint(fields=('snapshot', 'metric_code'), name='metric_value_unique'),
        ),
    ]
