# Generated by Django 5.2.17 on 2026-09-25 20:16

import django.db.models.deletion
import pme360.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('organizations', '0002_rls'),
        ('pmes', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_category',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('period_kind', models.CharField(choices=[('AUCUNE', 'Aucune'), ('MOIS', 'Mois'), ('TRIMESTRE', 'Trimestre'), ('SEMESTRE', 'Semestre'), ('ANNEE', 'Année'), ('EXERCICE', 'Exercice comptable')], default='AUCUNE', max_length=10)),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Durée de validité depuis la délivrance.', null=True)),
                ('freshness_days', models.PositiveIntegerField(blank=True, help_text='« À jour » si daté de moins de N jours.', null=True)),
                ('evidence_level', models.PositiveSmallIntegerField(default=3, help_text='Niveau de critère prouvé par ce document.')),
                ('sensitive', models.BooleanField(default=False, help_text='Données personnelles : jamais envoyé à une IA externe.')),
                ('guidance', models.TextField(blank=True, help_text="Comment l'obtenir / le préparer (langage simple).")),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_types', to='documents.documentcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_type',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('integrity_status', models.CharField(choices=[('EN_SCAN', 'Analyse de sécurité en cours'), ('SAIN', 'Sain'), ('REJETE_SECURITE', 'Rejeté (sécurité)')], default='EN_SCAN', max_length=16)),
                ('validity_status', models.CharField(choices=[('VALIDE', 'Valide'), ('EXPIRE', 'Expiré'), ('INDETERMINE', 'Indéterminée')], default='INDETERMINE', max_length=12)),
                ('currency_status', models.CharField(choices=[('A_JOUR', 'À jour'), ('PERIODE_ANTERIEURE', 'Période antérieure'), ('PERIODE_INCORRECTE', 'Période incorrecte'), ('INDETERMINE', 'Indéterminée')], default='INDETERMINE', max_length=20)),
                ('verification_status', models.CharField(choices=[('NON_VERIFIE', 'Non vérifié'), ('ANALYSE_IA', "Analysé par l'IA"), ('VERIF_HUMAINE_REQUISE', 'Vérification humaine requise'), ('VERIFIE_HUMAIN', 'Vérifié'), ('REJETE', 'Rejeté')], default='NON_VERIFIE', max_length=22)),
                ('conformity_status', models.CharField(choices=[('NON_EVALUE', 'Non évalué'), ('CONFORME', 'Conforme'), ('CONFORME_SOUS_RESERVE', 'Conforme sous réserve'), ('NON_CONFORME', 'Non conforme'), ('INCOHERENT', 'Incohérent')], default='NON_EVALUE', max_length=22)),
                ('decision_reason', models.TextField(blank=True, help_text='Motif en langage simple, visible par la PME.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_via', models.CharField(choices=[('PORTAIL_PME', 'Portail PME'), ('CONSEILLER', 'Conseiller')], max_length=12)),
                ('current_version_no', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deadline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='compliance.deadline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='pmes.pme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype')),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('storage_key', models.CharField(blank=True, help_text='Vide si le fichier a été refusé.', max_length=300)),
                ('original_filename', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=8)),
                ('mime_detected', models.CharField(max_length=120)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('av_status', models.CharField(choices=[('SAIN', 'Sain'), ('INFECTE', 'Infecté')], max_length=8)),
                ('av_engine', models.CharField(max_length=40)),
                ('av_signature', models.CharField(blank=True, max_length=200)),
                ('text_status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TEXTE_NATIF', 'Texte natif extrait'), ('OCR_REQUIS', 'Lecture optique requise (phase 4)'), ('ERREUR', 'Erreur de lecture')], default='EN_ATTENTE', max_length=12)),
                ('text_content', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='documents.document')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_version',
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCheck',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_code', models.CharField(max_length=40)),
                ('result', models.CharField(choices=[('OK', 'OK'), ('ALERTE', 'Alerte'), ('ECHEC', 'Échec'), ('NON_DETERMINE', 'Non déterminé')], max_length=14)),
                ('message', models.CharField(max_length=300)),
                ('details', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='documents.documentversion')),
            ],
            options={
                'db_table': 'document_check',
            },
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='document_category_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='document_type_unique_code'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'pme', 'document_type'], name='document_pme_type_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'verification_status'], name='document_verification_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_no'), name='document_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.CheckConstraint(condition=models.Q(('av_status', 'SAIN'), ('storage_key', ''), _connector='OR'), name='document_version_infected_never_stored'),
        ),
        migrations.AddConstraint(
            model_name='documentcheck',
            constraint=models.UniqueConstraint(fields=('version', 'check_code'), name='document_check_unique'),
        ),
    ]
