"""Contenu du référentiel GUDE-360 v1.0.0 (Document 5 : dimensions et critères ; Document 6 : indicateurs, niveaux).

STATUT : proposition à valider en atelier avec les conseillers GUDE-PME et un expert-comptable (décision D-04).
Les poids, ancres, bandes et règles ci-dessous sont des DONNÉES chargées en base, modifiables par publication
d'une nouvelle version : le moteur de scoring ne contient aucune de ces valeurs.

Choix de la politique de preuve (RM-01) : ``REQUIRED`` pour les critères de conformité (lentille C) qui ont un
justificatif identifié, ``RECOMMENDED`` pour les pratiques d'organisation documentées. Tant qu'aucune preuve n'est
vérifiée (phase 3), un critère ``REQUIRED`` est plafonné au niveau déclaratif (2).
"""

VERSION = "1.0.0"
FRAMEWORK_CODE = "GUDE-360"
FRAMEWORK_NAME = "Diagnostic 360° GUDE-PME"

PILLARS = [
    ("A", "Conformité & gouvernance", 30),
    ("B", "Performance & pilotage", 50),
    ("C", "Résilience & croissance", 20),
]

# (code, pilier, nom court, nom, poids, part du module sectoriel, description)
DIMENSIONS = [
    (
        "D01",
        "A",
        "Formalisation",
        "Formalisation juridique & gouvernance",
        10,
        0,
        "Existence légale, statuts, organes de décision et règles de fonctionnement.",
    ),
    (
        "D02",
        "A",
        "Fiscalité",
        "Conformité fiscale",
        10,
        0,
        "Déclarations et paiements fiscaux, régularité et cohérence avec l'activité.",
    ),
    (
        "D03",
        "A",
        "CNPS / Social",
        "Conformité sociale (CNPS) & droit du travail",
        10,
        0,
        "Déclaration des salariés, cotisations CNPS, contrats et registres du personnel.",
    ),
    (
        "D04",
        "B",
        "Finance",
        "Finance & comptabilité",
        15,
        0,
        "Tenue de la comptabilité, pilotage financier et indicateurs de performance.",
    ),
    (
        "D05",
        "B",
        "Stratégie",
        "Stratégie & modèle économique",
        7,
        0,
        "Vision, proposition de valeur, positionnement et feuille de route.",
    ),
    (
        "D06",
        "B",
        "Commercial",
        "Commercial, marketing & clients",
        8,
        0,
        "Connaissance des clients, processus de vente, marketing et dépendance commerciale.",
    ),
    (
        "D07",
        "B",
        "Opérations",
        "Opérations, qualité & conformité sectorielle",
        8,
        15,
        "Processus, achats, stocks, qualité, coûts et exigences propres au secteur.",
    ),
    (
        "D08",
        "B",
        "RH & organisation",
        "Ressources humaines & organisation",
        7,
        0,
        "Organisation, compétences, formation, rémunération et dépendance au dirigeant.",
    ),
    (
        "D09",
        "B",
        "Digital",
        "Digitalisation & systèmes d'information",
        5,
        0,
        "Équipements, logiciels, sauvegardes, cybersécurité et usages numériques.",
    ),
    (
        "D10",
        "C",
        "Risques",
        "Risques, contrôle interne & continuité",
        8,
        0,
        "Identification des risques, contrôle interne, assurances et continuité d'activité.",
    ),
    (
        "D11",
        "C",
        "Financement",
        "Financement & accès aux opportunités",
        6,
        0,
        "Besoin de financement, relation bancaire, marchés publics et partenariats.",
    ),
    (
        "D12",
        "C",
        "Innovation",
        "Innovation & croissance",
        6,
        0,
        "Nouveaux produits et marchés, démarche d'innovation et capacité de croissance.",
    ),
]

# Ancres génériques par lentille (Document 5, § 4), en langage simple pour la PME.
GENERIC_ANCHORS = {
    "O": [
        "Cela n'existe pas dans l'entreprise.",
        "Cela se fait de façon informelle, au cas par cas, sans rien d'écrit.",
        "C'est écrit ou organisé, mais appliqué seulement en partie.",
        "C'est appliqué régulièrement et nous pouvons le montrer.",
        "C'est suivi, mesuré et amélioré dans la durée.",
    ],
    "C": [
        "Non, ce n'est pas fait.",
        "En partie seulement, ou avec des retards importants.",
        "Oui, mais nous n'avons pas tous les justificatifs.",
        "Oui, c'est à jour et nous avons les justificatifs.",
        "Oui, à jour, justifié et suivi avec un calendrier et un responsable.",
    ],
    "R": [
        "Ce risque n'est ni identifié ni maîtrisé.",
        "Le risque est connu, mais rien n'est fait pour le réduire.",
        "Quelques mesures existent, sans suivi régulier.",
        "Des mesures sont en place et appliquées.",
        "Le risque est suivi régulièrement et les mesures sont revues.",
    ],
    "P": [
        "Aucun résultat sur ce point.",
        "Résultats faibles ou ponctuels.",
        "Résultats moyens.",
        "Bons résultats, réguliers.",
        "Très bons résultats, en progression.",
    ],
}

# Règles d'applicabilité (JSON Logic sur le profil de la PME).
HAS_EMPLOYEES = {">=": [{"var": "headcount"}, 1]}
IS_COMPANY = {"==": [{"var": "is_company"}, True]}
FAMILY = {"==": [{"var": "is_family_business"}, True]}
HAS_STOCK = {"==": [{"var": "has_stock"}, True]}
HAS_PRODUCTION = {"==": [{"var": "has_production"}, True]}
AGE_2Y = {">=": [{"var": "company_age_years"}, 2]}

# Critère : dict avec les clés
#   code, dim, name, lens, weight, critical?, evidence (REQUIRED|RECOMMENDED|NONE), docs, when (applicabilité),
#   q (question), why, anchors (sinon ancres génériques), audience, hint (preuve), module (code secteur)
CRITERIA = [
    # --- D01 Formalisation juridique & gouvernance ---------------------------------------------------------------
    dict(
        code="FOR-01",
        dim="D01",
        name="Existence légale et immatriculation au RCCM",
        lens="C",
        weight=20,
        critical=True,
        evidence="REQUIRED",
        docs=["RCCM"],
        q="Votre entreprise est-elle immatriculée au Registre du commerce (RCCM) ?",
        why="L'immatriculation est la base de l'existence légale : sans elle, pas de contrat, de banque ni de marché public.",
        anchors=[
            "Non, l'entreprise n'est pas immatriculée.",
            "Une démarche d'immatriculation est en cours.",
            "Oui, mais les informations du RCCM ne sont plus à jour (adresse, dirigeant, activité).",
            "Oui, immatriculée et à jour, et nous avons l'extrait RCCM.",
            "Oui, à jour, et chaque changement est déclaré sans délai.",
        ],
        hint="Extrait ou certificat RCCM",
    ),
    dict(
        code="FOR-02",
        dim="D01",
        name="Statuts à jour et cohérents avec la réalité",
        lens="C",
        weight=12,
        evidence="REQUIRED",
        docs=["STATUTS"],
        when=IS_COMPANY,
        q="Les statuts de la société correspondent-ils à la réalité (capital, associés, dirigeants) ?",
        why="Des statuts à jour évitent les conflits entre associés et les blocages avec les banques.",
        hint="Statuts à jour",
    ),
    dict(
        code="FOR-03",
        dim="D01",
        name="Identification fiscale (DFE / NCC)",
        lens="C",
        weight=13,
        critical=True,
        evidence="REQUIRED",
        docs=["DFE"],
        q="Votre entreprise a-t-elle fait sa déclaration fiscale d'existence (numéro de compte contribuable) ?",
        why="Le numéro de compte contribuable est indispensable pour facturer, déclarer et accéder aux marchés.",
        anchors=[
            "Non, nous n'avons pas de numéro de compte contribuable.",
            "La démarche est en cours.",
            "Oui, mais nous n'avons pas le document sous la main.",
            "Oui, et nous avons la DFE.",
            "Oui, et les informations fiscales sont mises à jour à chaque changement.",
        ],
        hint="Déclaration fiscale d'existence",
    ),
    dict(
        code="FOR-04",
        dim="D01",
        name="Organes de décision fonctionnels (AG, PV, décisions formalisées)",
        lens="O",
        weight=12,
        evidence="RECOMMENDED",
        docs=["PV_AG"],
        when=IS_COMPANY,
        q="Les décisions importantes sont-elles prises en assemblée et écrites dans des procès-verbaux ?",
        why="Des décisions écrites protègent l'entreprise et rassurent les partenaires financiers.",
        hint="PV d'assemblée",
    ),
    dict(
        code="FOR-05",
        dim="D01",
        name="Séparation du patrimoine personnel et professionnel",
        lens="O",
        weight=13,
        q="L'argent de l'entreprise est-il séparé de l'argent personnel du dirigeant (compte bancaire dédié, pas de caisse commune) ?",
        why="Mélanger les deux empêche de connaître la vraie rentabilité et fragilise l'entreprise.",
        anchors=[
            "Non, c'est la même caisse et le même compte.",
            "Nous essayons, mais c'est souvent mélangé.",
            "Il y a un compte d'entreprise, mais des dépenses personnelles y passent encore.",
            "Oui, tout est séparé et les retraits du dirigeant sont justifiés.",
            "Oui, séparé, et la rémunération du dirigeant est fixée et suivie.",
        ],
    ),
    dict(
        code="FOR-06",
        dim="D01",
        name="Délégations de pouvoir et signatures définies",
        lens="O",
        weight=8,
        evidence="RECOMMENDED",
        docs=["DELEGATIONS"],
        q="Est-il clairement défini qui peut signer et engager l'entreprise (contrats, paiements) ?",
        why="Savoir qui peut engager l'entreprise limite les erreurs et les fraudes.",
    ),
    dict(
        code="FOR-07",
        dim="D01",
        name="Contrats structurants écrits (bail, clients et fournisseurs clés)",
        lens="O",
        weight=10,
        evidence="RECOMMENDED",
        docs=["CONTRATS_CLES"],
        q="Avez-vous des contrats écrits avec vos principaux clients, fournisseurs et pour votre local ?",
        why="Un contrat écrit protège en cas de litige et facilite l'accès au crédit.",
    ),
    dict(
        code="FOR-08",
        dim="D01",
        name="Gouvernance familiale clarifiée",
        lens="O",
        weight=6,
        when=FAMILY,
        q="Dans cette entreprise familiale, les rôles de chacun et les règles de succession sont-ils clairs ?",
        why="Des règles claires évitent les conflits familiaux qui mettent l'entreprise en danger.",
    ),
    dict(
        code="FOR-09",
        dim="D01",
        name="Procédures administratives internes documentées",
        lens="O",
        weight=6,
        evidence="RECOMMENDED",
        docs=["MANUEL_PROC"],
        q="Les procédures administratives (courrier, archivage, validation des dépenses) sont-elles écrites ?",
        why="Des procédures écrites rendent l'entreprise moins dépendante d'une seule personne.",
    ),
    # --- D02 Conformité fiscale ----------------------------------------------------------------------------------
    dict(
        code="FIS-01",
        dim="D02",
        name="Régime d'imposition identifié et cohérent avec le chiffre d'affaires",
        lens="C",
        weight=12,
        evidence="REQUIRED",
        docs=["DFE"],
        q="Connaissez-vous votre régime d'imposition et correspond-il à votre chiffre d'affaires ?",
        why="Un régime inadapté expose à des redressements ou à des impôts mal calculés.",
    ),
    dict(
        code="FIS-02",
        dim="D02",
        name="Déclarations fiscales périodiques déposées dans les délais",
        lens="C",
        weight=25,
        critical=True,
        evidence="REQUIRED",
        docs=["DECL_FISCALE_PERIODIQUE"],
        q="Vos déclarations fiscales sont-elles déposées à temps ?",
        why="Les retards entraînent des pénalités et bloquent l'obtention de l'attestation de régularité fiscale.",
        anchors=[
            "Non, nous ne faisons pas de déclarations.",
            "Irrégulièrement, avec des retards fréquents.",
            "La plupart du temps à temps, mais sans tous les justificatifs de dépôt.",
            "Toujours à temps, avec les justificatifs de dépôt.",
            "Toujours à temps, avec un calendrier fiscal suivi par un responsable ou un conseil.",
        ],
        hint="Preuves de dépôt des dernières déclarations",
    ),
    dict(
        code="FIS-03",
        dim="D02",
        name="Paiements effectués et absence d'arriérés fiscaux",
        lens="C",
        weight=20,
        critical=True,
        evidence="REQUIRED",
        docs=["PREUVE_PAIEMENT_FISC", "ATTEST_REGUL_FISC"],
        q="Vos impôts sont-ils payés sans arriérés ?",
        why="Les arriérés fiscaux s'accumulent avec des pénalités et bloquent l'accès aux marchés publics.",
        anchors=[
            "Non, nous avons des arriérés importants sans solution.",
            "Des arriérés existent ; un échéancier est en discussion.",
            "Pas d'arriérés connus, mais nous n'avons pas tous les justificatifs.",
            "Tout est payé et nous avons les quittances.",
            "Tout est payé, justifié, et les échéances sont anticipées dans la trésorerie.",
        ],
        hint="Quittances ou attestation de régularité fiscale",
    ),
    dict(
        code="FIS-04",
        dim="D02",
        name="Attestation de régularité fiscale en cours de validité",
        lens="C",
        weight=15,
        evidence="REQUIRED",
        docs=["ATTEST_REGUL_FISC"],
        q="Disposez-vous d'une attestation de régularité fiscale valide ?",
        why="Cette attestation est souvent exigée par les banques, les grands clients et les marchés publics.",
        anchors=[
            "Non, et nous ne pourrions pas l'obtenir aujourd'hui.",
            "Non, mais nous pourrions l'obtenir après régularisation.",
            "Nous en avons eu une, mais elle a expiré.",
            "Oui, en cours de validité.",
            "Oui, et nous la renouvelons avant expiration.",
        ],
        hint="Attestation de régularité fiscale",
    ),
    dict(
        code="FIS-05",
        dim="D02",
        name="Dépôt annuel des états financiers auprès de l'administration",
        lens="C",
        weight=13,
        evidence="REQUIRED",
        docs=["ETATS_FIN_SYSCOHADA"],
        q="Déposez-vous chaque année vos états financiers auprès de l'administration fiscale ?",
        why="Le dépôt des états financiers est une obligation et la base de tout dossier de financement.",
    ),
    dict(
        code="FIS-06",
        dim="D02",
        name="Cohérence entre activité réelle et déclarations",
        lens="R",
        weight=10,
        q="Le chiffre d'affaires déclaré aux impôts correspond-il au chiffre d'affaires réel de l'entreprise ?",
        why="Un écart entre activité réelle et déclarations est un risque fiscal majeur en cas de contrôle.",
        anchors=[
            "Non, l'écart est important.",
            "Il y a des écarts que nous ne savons pas expliquer.",
            "Globalement oui, avec quelques écarts.",
            "Oui, les montants concordent.",
            "Oui, et un rapprochement est fait à chaque déclaration.",
        ],
    ),
    dict(
        code="FIS-07",
        dim="D02",
        name="Organisation de la documentation fiscale",
        lens="O",
        weight=5,
        q="Vos documents fiscaux (déclarations, quittances, courriers) sont-ils classés et faciles à retrouver ?",
        why="Un classement rigoureux permet de répondre vite à un contrôle et d'éviter les pénalités.",
    ),
    # --- D03 Conformité sociale ----------------------------------------------------------------------------------
    dict(
        code="SOC-01",
        dim="D03",
        name="Immatriculation employeur à la CNPS",
        lens="C",
        weight=15,
        critical=True,
        evidence="REQUIRED",
        docs=["IMMAT_CNPS"],
        when=HAS_EMPLOYEES,
        q="Votre entreprise est-elle immatriculée comme employeur à la CNPS ?",
        why="L'immatriculation est obligatoire dès le premier salarié et protège vos employés.",
        anchors=[
            "Non.",
            "La démarche est en cours.",
            "Oui, mais nous ne retrouvons pas le justificatif.",
            "Oui, et nous avons l'attestation d'immatriculation.",
            "Oui, et les informations sont tenues à jour.",
        ],
        hint="Attestation d'immatriculation employeur",
    ),
    dict(
        code="SOC-02",
        dim="D03",
        name="Déclaration de tous les salariés",
        lens="C",
        weight=20,
        critical=True,
        evidence="REQUIRED",
        docs=["DECL_CNPS_PERIODIQUE"],
        when=HAS_EMPLOYEES,
        q="Tous vos salariés sont-ils déclarés à la CNPS ?",
        why="Un salarié non déclaré n'est pas protégé et expose l'entreprise à des redressements.",
        anchors=[
            "Aucun salarié n'est déclaré.",
            "Une minorité des salariés est déclarée.",
            "La plupart des salariés sont déclarés.",
            "Tous les salariés sont déclarés, justificatifs à l'appui.",
            "Tous déclarés, et chaque entrée ou sortie est déclarée sans délai.",
        ],
        hint="Déclaration CNPS de la dernière période",
    ),
    dict(
        code="SOC-03",
        dim="D03",
        name="Déclarations et cotisations CNPS à jour",
        lens="C",
        weight=25,
        critical=True,
        evidence="REQUIRED",
        docs=["DECL_CNPS_PERIODIQUE", "PREUVE_PAIEMENT_CNPS", "ATTEST_CNPS"],
        when=HAS_EMPLOYEES,
        q="Vos déclarations et cotisations CNPS sont-elles faites et payées à chaque échéance ?",
        why="Les retards de cotisations génèrent des majorations et privent les salariés de leurs droits.",
        anchors=[
            "Non, nous ne déclarons ni ne payons.",
            "Irrégulièrement, avec des retards.",
            "La plupart du temps, mais sans tous les justificatifs.",
            "Oui, à chaque échéance, avec les justificatifs.",
            "Oui, à chaque échéance, avec un calendrier suivi et des paiements anticipés.",
        ],
        hint="Déclarations et preuves de paiement CNPS récentes",
    ),
    dict(
        code="SOC-04",
        dim="D03",
        name="Absence d'arriérés CNPS ou plan d'apurement respecté",
        lens="R",
        weight=10,
        evidence="RECOMMENDED",
        docs=["ATTEST_CNPS"],
        when=HAS_EMPLOYEES,
        q="Avez-vous des arriérés de cotisations CNPS ?",
        why="Les arriérés sociaux sont une dette prioritaire qui peut bloquer l'entreprise.",
        anchors=[
            "Oui, des arriérés importants sans solution.",
            "Oui, un plan d'apurement est en discussion.",
            "Oui, un plan d'apurement est signé et respecté.",
            "Non, aucun arriéré.",
            "Non, et nous disposons d'une attestation de situation à jour.",
        ],
    ),
    dict(
        code="SOC-05",
        dim="D03",
        name="Contrats de travail écrits",
        lens="C",
        weight=15,
        evidence="REQUIRED",
        docs=["CONTRAT_TRAVAIL_ECHANTILLON"],
        when=HAS_EMPLOYEES,
        q="Vos salariés ont-ils un contrat de travail écrit ?",
        why="Le contrat écrit protège l'employeur comme le salarié en cas de désaccord.",
        anchors=[
            "Aucun contrat écrit.",
            "Quelques contrats seulement.",
            "La plupart des salariés ont un contrat.",
            "Tous les salariés ont un contrat signé.",
            "Tous, avec des contrats revus et des avenants à jour.",
        ],
    ),
    dict(
        code="SOC-06",
        dim="D03",
        name="Tenue des registres et bulletins de paie",
        lens="C",
        weight=10,
        evidence="REQUIRED",
        docs=["BULLETIN_PAIE_ECHANTILLON"],
        when=HAS_EMPLOYEES,
        q="Remettez-vous un bulletin de paie à chaque salarié et tenez-vous un registre du personnel ?",
        why="Les bulletins et le registre sont obligatoires et prouvent le respect des droits des salariés.",
    ),
    dict(
        code="SOC-07",
        dim="D03",
        name="Santé et sécurité au travail (dispositions minimales)",
        lens="C",
        weight=5,
        q="Des mesures de santé et de sécurité sont-elles prises pour vos salariés (équipements, trousse de secours, consignes) ?",
        why="La sécurité au travail évite les accidents et leurs conséquences humaines et financières.",
    ),
    # --- D04 Finance & comptabilité ------------------------------------------------------------------------------
    dict(
        code="FIN-01",
        dim="D04",
        name="Tenue d'une comptabilité régulière (SYSCOHADA normal ou SMT)",
        lens="C",
        weight=12,
        critical=True,
        evidence="REQUIRED",
        docs=["ETATS_FIN_SYSCOHADA"],
        q="Tenez-vous une comptabilité qui produit chaque année un bilan et un compte de résultat ?",
        why="La comptabilité est la base de toute décision et de tout dossier de financement.",
        anchors=[
            "Non, aucune comptabilité.",
            "Seulement un cahier de recettes et de dépenses.",
            "Une comptabilité est tenue, mais les états financiers ne sont pas produits chaque année.",
            "Oui, les états financiers sont produits chaque année.",
            "Oui, et des situations intermédiaires sont produites en cours d'année.",
        ],
        hint="États financiers du dernier exercice",
    ),
    dict(
        code="FIN-02",
        dim="D04",
        name="Qualité de la comptabilité (expert-comptable, CGA, états visés)",
        lens="O",
        weight=8,
        evidence="RECOMMENDED",
        docs=["ETATS_FIN_SYSCOHADA"],
        q="Votre comptabilité est-elle tenue ou vérifiée par un professionnel (expert-comptable, centre de gestion agréé) ?",
        why="Une comptabilité fiable donne confiance aux banques et évite les erreurs coûteuses.",
    ),
    dict(
        code="FIN-03",
        dim="D04",
        name="Suivi de trésorerie",
        lens="O",
        weight=10,
        evidence="RECOMMENDED",
        docs=["TABLEAU_TRESORERIE"],
        q="Comment suivez-vous l'argent qui entre et qui sort de votre entreprise ?",
        why="Savoir à l'avance quand la trésorerie manquera permet d'éviter les retards de paiement.",
        anchors=[
            "Je ne fais pas de suivi particulier.",
            "Je regarde mon solde bancaire ou ma caisse de temps en temps.",
            "J'ai un tableau (cahier ou Excel) mis à jour de temps en temps.",
            "J'ai un tableau de trésorerie mis à jour chaque semaine ou chaque mois, et je rapproche avec la banque.",
            "J'ai des prévisions sur 3 à 6 mois que je compare au réel chaque mois.",
        ],
        hint="Tableau de trésorerie des 3 derniers mois",
    ),
    dict(
        code="FIN-04",
        dim="D04",
        name="Reporting de gestion périodique",
        lens="O",
        weight=8,
        evidence="RECOMMENDED",
        docs=["TABLEAU_BORD_FIN"],
        q="Suivez-vous chaque mois ou chaque trimestre vos ventes, vos charges et votre résultat ?",
        why="Un tableau de bord régulier permet de réagir vite quand les résultats se dégradent.",
    ),
    dict(
        code="FIN-05",
        dim="D04",
        name="Budget et prévisions financières",
        lens="O",
        weight=7,
        evidence="RECOMMENDED",
        docs=["BUDGET", "PREVISIONNEL"],
        q="Préparez-vous un budget annuel ou des prévisions financières ?",
        why="Un budget aide à anticiper les besoins et à négocier avec les banques.",
    ),
    dict(code="FIN-06", dim="D04", name="Rentabilité (marge nette, EBE / CA)", lens="P", weight=12),
    dict(code="FIN-07", dim="D04", name="Croissance du chiffre d'affaires", lens="P", weight=8, when=AGE_2Y),
    dict(code="FIN-08", dim="D04", name="Structure financière et solvabilité", lens="P", weight=10),
    dict(code="FIN-09", dim="D04", name="Liquidité et besoin en fonds de roulement", lens="P", weight=10),
    dict(code="FIN-10", dim="D04", name="Capacité de remboursement", lens="P", weight=8),
    dict(code="FIN-11", dim="D04", name="Concentration clients et fournisseurs", lens="R", weight=7),
    # --- D05 Stratégie & modèle économique -----------------------------------------------------------------------
    dict(
        code="STR-01",
        dim="D05",
        name="Vision, mission et objectifs formalisés et partagés",
        lens="O",
        weight=15,
        evidence="RECOMMENDED",
        docs=["PLAN_STRATEGIQUE"],
        q="Avez-vous défini par écrit où vous voulez amener l'entreprise dans 3 à 5 ans, et votre équipe le sait-elle ?",
        why="Une direction claire aide à prendre les bonnes décisions et à mobiliser l'équipe.",
    ),
    dict(
        code="STR-02",
        dim="D05",
        name="Proposition de valeur et segments clients clairs",
        lens="O",
        weight=20,
        evidence="RECOMMENDED",
        docs=["BUSINESS_MODEL"],
        q="Savez-vous précisément qui sont vos clients cibles et pourquoi ils vous choisissent plutôt qu'un concurrent ?",
        why="Connaître sa valeur pour le client est la base d'une stratégie commerciale efficace.",
    ),
    dict(
        code="STR-03",
        dim="D05",
        name="Positionnement et avantage concurrentiel identifiés",
        lens="O",
        weight=15,
        q="Connaissez-vous vos principaux concurrents et ce qui vous distingue d'eux ?",
        why="Connaître la concurrence permet de fixer ses prix et de défendre ses clients.",
    ),
    dict(
        code="STR-04",
        dim="D05",
        name="Plan d'affaires ou feuille de route à jour (moins de 2 ans)",
        lens="O",
        weight=20,
        evidence="RECOMMENDED",
        docs=["BUSINESS_PLAN", "FEUILLE_ROUTE"],
        q="Avez-vous un plan d'affaires ou une feuille de route de moins de 2 ans ?",
        why="Un plan d'affaires à jour est demandé par la plupart des financeurs.",
    ),
    dict(
        code="STR-05",
        dim="D05",
        name="Diversification (produits, clients, marchés)",
        lens="R",
        weight=15,
        q="Votre activité repose-t-elle sur plusieurs produits, clients ou marchés ?",
        why="Dépendre d'un seul produit ou marché rend l'entreprise vulnérable au moindre choc.",
        anchors=[
            "Un seul produit et un seul marché.",
            "Très peu de diversification.",
            "Quelques produits ou marchés.",
            "Plusieurs produits et marchés, aucun ne dépasse la moitié du chiffre d'affaires.",
            "Activité bien diversifiée, suivie et ajustée chaque année.",
        ],
    ),
    dict(
        code="STR-06",
        dim="D05",
        name="Suivi des objectifs stratégiques",
        lens="O",
        weight=15,
        q="Faites-vous au moins une fois par an le point sur vos objectifs et vos résultats ?",
        why="Faire le point régulièrement permet de corriger la trajectoire à temps.",
    ),
    # --- D06 Commercial, marketing & clients ---------------------------------------------------------------------
    dict(
        code="COM-01",
        dim="D06",
        name="Connaissance et suivi du portefeuille clients",
        lens="O",
        weight=15,
        evidence="RECOMMENDED",
        docs=["EXPORT_FICHIER_CLIENTS"],
        q="Avez-vous un fichier de vos clients (cahier, Excel ou logiciel) avec leurs achats ?",
        why="Connaître ses clients permet de les fidéliser et de vendre davantage.",
    ),
    dict(
        code="COM-02",
        dim="D06",
        name="Processus de vente et pipeline suivis",
        lens="O",
        weight=15,
        evidence="RECOMMENDED",
        docs=["TABLEAU_SUIVI_COMMERCIAL"],
        q="Suivez-vous vos prospects, devis et relances de façon organisée ?",
        why="Un suivi commercial organisé augmente le nombre de ventes conclues.",
    ),
    dict(
        code="COM-03",
        dim="D06",
        name="Politique de prix documentée",
        lens="O",
        weight=12,
        evidence="RECOMMENDED",
        docs=["GRILLE_TARIFAIRE"],
        q="Vos prix sont-ils calculés à partir de vos coûts et de la marge que vous voulez faire ?",
        why="Un prix mal calculé peut faire perdre de l'argent sur chaque vente.",
    ),
    dict(
        code="COM-04",
        dim="D06",
        name="Actions marketing et communication planifiées",
        lens="O",
        weight=10,
        evidence="RECOMMENDED",
        docs=["PLAN_MARKETING"],
        q="Planifiez-vous vos actions de promotion et de communication ?",
        why="Une communication régulière et ciblée attire de nouveaux clients à moindre coût.",
    ),
    dict(
        code="COM-05",
        dim="D06",
        name="Présence digitale (site, réseaux sociaux, annuaires)",
        lens="O",
        weight=10,
        q="Votre entreprise est-elle présente en ligne (site web, réseaux sociaux, annuaires) ?",
        why="La plupart des clients cherchent d'abord en ligne avant d'acheter.",
        anchors=[
            "Aucune présence en ligne.",
            "Une page ou un profil peu actif.",
            "Un site ou des réseaux sociaux animés de temps en temps.",
            "Une présence régulière qui nous apporte des clients.",
            "Une présence suivie avec des indicateurs (visites, contacts, ventes).",
        ],
    ),
    dict(
        code="COM-06",
        dim="D06",
        name="Satisfaction client et traitement des réclamations",
        lens="O",
        weight=13,
        evidence="RECOMMENDED",
        docs=["REGISTRE_RECLAMATIONS"],
        q="Mesurez-vous la satisfaction de vos clients et traitez-vous leurs réclamations de façon organisée ?",
        why="Un client mécontent bien traité devient souvent un client fidèle.",
    ),
    dict(
        code="COM-07",
        dim="D06",
        name="Canaux de distribution adaptés et diversifiés",
        lens="P",
        weight=10,
        q="Par combien de canaux vendez-vous (boutique, livraison, revendeurs, en ligne, appels d'offres) ?",
        why="Plusieurs canaux de vente réduisent la dépendance et augmentent les ventes.",
        anchors=[
            "Un seul canal, peu efficace.",
            "Un seul canal, qui fonctionne correctement.",
            "Deux canaux.",
            "Trois canaux ou plus, qui fonctionnent bien.",
            "Plusieurs canaux, suivis et optimisés.",
        ],
    ),
    dict(code="COM-08", dim="D06", name="Dépendance commerciale (part du premier client)", lens="R", weight=15),
    # --- D07 Opérations, qualité & conformité sectorielle (tronc commun : 85 points) ----------------------------
    dict(
        code="OPE-01",
        dim="D07",
        name="Processus clés cartographiés",
        lens="O",
        weight=12,
        evidence="RECOMMENDED",
        docs=["CARTO_PROCESSUS"],
        q="Les principales étapes de votre activité (de la commande à la livraison) sont-elles décrites ?",
        why="Des processus décrits permettent de former plus vite et de réduire les erreurs.",
    ),
    dict(
        code="OPE-02",
        dim="D07",
        name="Gestion des achats et des fournisseurs",
        lens="O",
        weight=12,
        evidence="RECOMMENDED",
        docs=["PROC_ACHATS"],
        q="Mettez-vous vos fournisseurs en concurrence et suivez-vous vos achats avec une procédure ?",
        why="Des achats bien gérés améliorent directement la marge.",
    ),
    dict(
        code="OPE-03",
        dim="D07",
        name="Gestion des stocks (inventaire, suivi)",
        lens="O",
        weight=10,
        evidence="RECOMMENDED",
        docs=["ETAT_STOCKS"],
        when=HAS_STOCK,
        q="Faites-vous des inventaires et suivez-vous vos stocks régulièrement ?",
        why="Des stocks mal suivis immobilisent de l'argent et favorisent les pertes et les vols.",
    ),
    dict(
        code="OPE-04",
        dim="D07",
        name="Maîtrise des délais et de la qualité",
        lens="P",
        weight=12,
        q="Respectez-vous vos délais de livraison et la qualité promise à vos clients ?",
        why="La régularité des délais et de la qualité fidélise les clients.",
        anchors=[
            "Retards et problèmes de qualité fréquents.",
            "Retards ou défauts assez fréquents.",
            "Respectés la plupart du temps.",
            "Presque toujours respectés, et mesurés.",
            "Toujours respectés, mesurés et améliorés.",
        ],
    ),
    dict(
        code="OPE-05",
        dim="D07",
        name="Équipements et maintenance",
        lens="O",
        weight=8,
        evidence="RECOMMENDED",
        docs=["PLAN_MAINTENANCE"],
        when=HAS_PRODUCTION,
        q="Vos équipements font-ils l'objet d'un entretien planifié ?",
        why="L'entretien préventif évite les pannes qui arrêtent la production.",
    ),
    dict(
        code="OPE-06",
        dim="D07",
        name="Calcul et maîtrise des coûts de revient",
        lens="O",
        weight=10,
        q="Connaissez-vous le coût de revient de chacun de vos produits ou services ?",
        why="Sans coût de revient, impossible de savoir quels produits sont rentables.",
    ),
    dict(
        code="OPE-07",
        dim="D07",
        name="Capacité de production et productivité connues",
        lens="P",
        weight=8,
        q="Connaissez-vous votre capacité maximale de production ou de service et votre taux d'utilisation ?",
        why="Connaître sa capacité permet d'accepter les commandes sans risque de retard.",
        anchors=[
            "Non, nous ne la connaissons pas.",
            "Approximativement.",
            "Oui, estimée mais pas suivie.",
            "Oui, suivie régulièrement.",
            "Oui, suivie et améliorée avec des objectifs de productivité.",
        ],
    ),
    dict(
        code="OPE-08",
        dim="D07",
        name="Démarche qualité (procédures qualité, certification éventuelle)",
        lens="O",
        weight=13,
        evidence="RECOMMENDED",
        docs=["CERTIFICAT", "MANUEL_QUALITE"],
        q="Avez-vous une démarche qualité (procédures, contrôles, certification ISO ou autre) ?",
        why="Une démarche qualité ouvre l'accès aux grands clients et aux marchés exigeants.",
    ),
    # Modules sectoriels (15 points ; exigences réglementaires à valider, registre Document 8 « à vérifier »)
    dict(
        code="OPE-AGR-01",
        dim="D07",
        module="AGROALIMENTAIRE",
        name="Hygiène et bonnes pratiques de fabrication",
        lens="C",
        weight=5,
        evidence="RECOMMENDED",
        q="Des règles d'hygiène et de bonnes pratiques de fabrication sont-elles appliquées ?",
        why="L'hygiène protège les consommateurs et conditionne l'accès aux distributeurs.",
    ),
    dict(
        code="OPE-AGR-02",
        dim="D07",
        module="AGROALIMENTAIRE",
        name="Traçabilité des lots",
        lens="O",
        weight=4,
        q="Pouvez-vous retrouver l'origine des matières premières et les clients de chaque lot produit ?",
        why="La traçabilité permet de retirer rapidement un lot en cas de problème.",
    ),
    dict(
        code="OPE-AGR-03",
        dim="D07",
        module="AGROALIMENTAIRE",
        name="Autorisations ou agréments sanitaires applicables",
        lens="C",
        weight=4,
        evidence="RECOMMENDED",
        docs=["AGREMENT_SANITAIRE"],
        q="Disposez-vous des autorisations sanitaires nécessaires à votre activité ?",
        why="Les autorisations sanitaires sont souvent exigées pour vendre en grande distribution.",
    ),
    dict(
        code="OPE-AGR-04",
        dim="D07",
        module="AGROALIMENTAIRE",
        name="Maîtrise de la chaîne du froid",
        lens="O",
        weight=2,
        q="Si vos produits l'exigent, la chaîne du froid est-elle maîtrisée et contrôlée ?",
        why="Une rupture de la chaîne du froid peut rendre les produits dangereux.",
    ),
    dict(
        code="OPE-BTP-01",
        dim="D07",
        module="BTP",
        name="Sécurité des chantiers (EPI, plan de prévention)",
        lens="C",
        weight=5,
        q="Vos chantiers respectent-ils les règles de sécurité (équipements de protection, plan de prévention) ?",
        why="Les accidents de chantier ont des conséquences humaines et financières graves.",
    ),
    dict(
        code="OPE-BTP-02",
        dim="D07",
        module="BTP",
        name="Agréments ou qualifications professionnelles",
        lens="C",
        weight=4,
        evidence="RECOMMENDED",
        docs=["AGREMENT_BTP"],
        q="Disposez-vous des agréments ou qualifications exigés pour vos marchés ?",
        why="Les agréments conditionnent l'accès à de nombreux marchés publics et privés.",
    ),
    dict(
        code="OPE-BTP-03",
        dim="D07",
        module="BTP",
        name="Assurances professionnelles",
        lens="C",
        weight=3,
        evidence="RECOMMENDED",
        docs=["ATTEST_ASSURANCE"],
        q="Êtes-vous couverts par les assurances professionnelles de votre métier ?",
        why="L'assurance protège l'entreprise contre les sinistres sur les ouvrages.",
    ),
    dict(
        code="OPE-BTP-04",
        dim="D07",
        module="BTP",
        name="Références de marchés exécutés",
        lens="P",
        weight=3,
        q="Pouvez-vous présenter des références de chantiers réalisés, avec attestations de bonne exécution ?",
        why="Les références sont décisives pour gagner de nouveaux marchés.",
        anchors=[
            "Aucune référence.",
            "Quelques chantiers sans attestation.",
            "Plusieurs chantiers, peu d'attestations.",
            "Plusieurs références attestées.",
            "De nombreuses références attestées, dont des marchés importants.",
        ],
    ),
    dict(
        code="OPE-IND-01",
        dim="D07",
        module="INDUSTRIE",
        name="Hygiène, sécurité, environnement et gestion des déchets",
        lens="C",
        weight=6,
        q="Les règles d'hygiène, de sécurité et de gestion des déchets sont-elles appliquées dans l'usine ?",
        why="Une bonne gestion HSE protège les salariés et évite les sanctions.",
    ),
    dict(
        code="OPE-IND-02",
        dim="D07",
        module="INDUSTRIE",
        name="Conformité environnementale applicable",
        lens="C",
        weight=5,
        evidence="RECOMMENDED",
        q="Votre activité respecte-t-elle les exigences environnementales qui s'y appliquent ?",
        why="La conformité environnementale est de plus en plus exigée par les clients et les financeurs.",
    ),
    dict(
        code="OPE-IND-03",
        dim="D07",
        module="INDUSTRIE",
        name="Sécurité des machines",
        lens="C",
        weight=4,
        q="Vos machines sont-elles équipées des protections et consignes de sécurité nécessaires ?",
        why="Des machines sécurisées évitent les accidents graves.",
    ),
    dict(
        code="OPE-COMM-01",
        dim="D07",
        module="COMMERCE",
        name="Gestion des stocks et de la démarque",
        lens="O",
        weight=6,
        q="Suivez-vous les pertes de marchandises (casse, vol, péremption) ?",
        why="La démarque non suivie peut absorber une grande partie de la marge.",
    ),
    dict(
        code="OPE-COMM-02",
        dim="D07",
        module="COMMERCE",
        name="Étiquetage et affichage des prix",
        lens="C",
        weight=4,
        q="Vos produits sont-ils correctement étiquetés et les prix affichés ?",
        why="L'étiquetage et l'affichage des prix sont des obligations envers les consommateurs.",
    ),
    dict(
        code="OPE-COMM-03",
        dim="D07",
        module="COMMERCE",
        name="Factures normalisées",
        lens="C",
        weight=5,
        evidence="RECOMMENDED",
        q="Émettez-vous des factures conformes aux exigences en vigueur (factures normalisées) ?",
        why="Des factures conformes sécurisent la déduction de TVA de vos clients et votre situation fiscale.",
    ),
    dict(
        code="OPE-SRV-01",
        dim="D07",
        module="SERVICES",
        name="Qualité de service (délais, engagements)",
        lens="O",
        weight=9,
        q="Vos engagements de service (délais, niveau de qualité) sont-ils écrits et suivis ?",
        why="Des engagements clairs et tenus fidélisent les clients.",
    ),
    dict(
        code="OPE-SRV-02",
        dim="D07",
        module="SERVICES",
        name="Confidentialité des informations clients",
        lens="O",
        weight=6,
        q="Les informations confidentielles de vos clients sont-elles protégées ?",
        why="La confidentialité est souvent une condition pour travailler avec les grandes entreprises.",
    ),
    dict(
        code="OPE-TEC-01",
        dim="D07",
        module="TECH",
        name="Sécurité des produits numériques",
        lens="O",
        weight=5,
        q="La sécurité de vos applications ou services est-elle testée régulièrement ?",
        why="Une faille de sécurité peut détruire la confiance des utilisateurs.",
    ),
    dict(
        code="OPE-TEC-02",
        dim="D07",
        module="TECH",
        name="Protection des données des utilisateurs",
        lens="C",
        weight=6,
        evidence="RECOMMENDED",
        q="Les données personnelles de vos utilisateurs sont-elles collectées et protégées conformément à la loi ?",
        why="La protection des données personnelles est une obligation légale et un facteur de confiance.",
    ),
    dict(
        code="OPE-TEC-03",
        dim="D07",
        module="TECH",
        name="Propriété du code et des actifs",
        lens="C",
        weight=4,
        q="L'entreprise est-elle propriétaire de son code, de ses marques et de ses noms de domaine ?",
        why="Sans propriété claire des actifs, l'entreprise est difficile à financer ou à vendre.",
    ),
    # --- D08 RH & organisation -----------------------------------------------------------------------------------
    dict(
        code="RHO-01",
        dim="D08",
        name="Organigramme à jour",
        lens="O",
        weight=12,
        evidence="RECOMMENDED",
        docs=["ORGANIGRAMME"],
        q="Avez-vous un organigramme à jour qui montre qui fait quoi ?",
        why="Un organigramme clarifie les responsabilités et facilite l'intégration des nouveaux.",
    ),
    dict(
        code="RHO-02",
        dim="D08",
        name="Fiches de poste pour les postes clés",
        lens="O",
        weight=12,
        evidence="RECOMMENDED",
        docs=["FICHES_POSTE"],
        q="Les postes clés ont-ils une fiche de poste écrite ?",
        why="Une fiche de poste évite les malentendus sur les missions de chacun.",
    ),
    dict(
        code="RHO-03",
        dim="D08",
        name="Recrutement structuré",
        lens="O",
        weight=8,
        q="Vos recrutements suivent-ils une méthode (définition du besoin, entretiens, période d'essai) ?",
        why="Un bon recrutement coûte moins cher qu'une erreur de recrutement.",
    ),
    dict(
        code="RHO-04",
        dim="D08",
        name="Plan de formation et formations réalisées",
        lens="O",
        weight=12,
        evidence="RECOMMENDED",
        docs=["PLAN_FORMATION"],
        q="Vos salariés bénéficient-ils de formations planifiées ?",
        why="La formation améliore la productivité et fidélise les salariés.",
    ),
    dict(
        code="RHO-05",
        dim="D08",
        name="Évaluation de la performance",
        lens="O",
        weight=10,
        q="Faites-vous des entretiens annuels avec vos salariés ?",
        why="L'entretien annuel permet de fixer des objectifs et de repérer les besoins.",
    ),
    dict(
        code="RHO-06",
        dim="D08",
        name="Politique de rémunération et gestion des congés",
        lens="O",
        weight=10,
        q="Les règles de rémunération et de congés sont-elles claires et appliquées de la même façon pour tous ?",
        why="Des règles claires réduisent les conflits et le départ des salariés.",
    ),
    dict(
        code="RHO-07",
        dim="D08",
        name="Turnover maîtrisé",
        lens="P",
        weight=10,
        when=HAS_EMPLOYEES,
        q="Les départs de salariés sont-ils rares dans votre entreprise ?",
        why="Des départs fréquents coûtent cher en recrutement et en formation.",
        anchors=[
            "Départs très fréquents, l'équipe change sans cesse.",
            "Départs fréquents.",
            "Quelques départs chaque année.",
            "Départs rares.",
            "Départs rares, suivis et analysés.",
        ],
    ),
    dict(
        code="RHO-08",
        dim="D08",
        name="Délégation managériale",
        lens="R",
        weight=14,
        q="L'entreprise peut-elle fonctionner normalement quelques semaines en l'absence du dirigeant ?",
        why="Une entreprise qui dépend d'une seule personne est très vulnérable.",
        anchors=[
            "Non, tout s'arrête sans le dirigeant.",
            "Difficilement, beaucoup de décisions attendent.",
            "Pour les tâches courantes, oui.",
            "Oui, les responsables décident dans leur domaine.",
            "Oui, les délégations sont écrites et régulièrement testées.",
        ],
    ),
    dict(
        code="RHO-09",
        dim="D08",
        name="Plan de succession des postes clés",
        lens="R",
        weight=12,
        q="Avez-vous prévu qui remplacerait les personnes clés en cas de départ ?",
        why="Anticiper les remplacements évite les crises en cas de départ imprévu.",
    ),
    # --- D09 Digitalisation & SI ---------------------------------------------------------------------------------
    dict(
        code="DIG-01",
        dim="D09",
        name="Équipements adaptés à l'activité",
        lens="O",
        weight=8,
        evidence="RECOMMENDED",
        docs=["INVENTAIRE_SI"],
        q="Vos équipements informatiques (ordinateurs, téléphones, imprimantes) sont-ils suffisants et en bon état ?",
        why="Des équipements adaptés font gagner du temps au quotidien.",
    ),
    dict(
        code="DIG-02",
        dim="D09",
        name="Logiciel de comptabilité ou de gestion",
        lens="O",
        weight=15,
        q="Utilisez-vous un logiciel de comptabilité ou de gestion ?",
        why="Un logiciel fiabilise les chiffres et fait gagner beaucoup de temps.",
        anchors=[
            "Non, tout est sur papier.",
            "Des tableaux Excel dispersés.",
            "Un logiciel utilisé en partie.",
            "Un logiciel utilisé pour toute la gestion courante.",
            "Un logiciel intégré qui produit des tableaux de bord.",
        ],
    ),
    dict(
        code="DIG-03",
        dim="D09",
        name="Outils métier (ERP, CRM, paie, stocks, caisse)",
        lens="O",
        weight=12,
        q="Utilisez-vous des outils numériques pour vos ventes, vos stocks, votre caisse ou la paie ?",
        why="Les outils métier réduisent les erreurs et donnent une vision en temps réel.",
    ),
    dict(
        code="DIG-04",
        dim="D09",
        name="Sauvegardes régulières et testées",
        lens="R",
        weight=15,
        evidence="RECOMMENDED",
        docs=["POLITIQUE_SAUVEGARDE"],
        q="Vos données (comptabilité, clients, documents) sont-elles sauvegardées régulièrement ?",
        why="Sans sauvegarde, une panne ou un vol d'ordinateur peut faire perdre des années de données.",
        anchors=[
            "Aucune sauvegarde.",
            "Des copies occasionnelles.",
            "Des sauvegardes régulières mais jamais testées.",
            "Des sauvegardes régulières, dont une hors des locaux.",
            "Des sauvegardes automatiques, testées régulièrement.",
        ],
    ),
    dict(
        code="DIG-05",
        dim="D09",
        name="Cybersécurité de base",
        lens="R",
        weight=15,
        evidence="RECOMMENDED",
        docs=["POLITIQUE_SI"],
        q="Appliquez-vous les règles de base de sécurité informatique (mots de passe, antivirus, mises à jour) ?",
        why="La plupart des attaques informatiques exploitent des négligences simples.",
    ),
    dict(
        code="DIG-06",
        dim="D09",
        name="Gestion documentaire numérique",
        lens="O",
        weight=10,
        q="Vos documents importants sont-ils numérisés et classés de façon à être retrouvés facilement ?",
        why="Des documents numérisés se retrouvent vite et ne se perdent pas.",
    ),
    dict(
        code="DIG-07",
        dim="D09",
        name="Digitalisation des processus (paiements, facturation, commandes)",
        lens="O",
        weight=10,
        q="Utilisez-vous le paiement mobile, la facturation électronique ou la prise de commande en ligne ?",
        why="Digitaliser les paiements et les commandes accélère l'encaissement.",
    ),
    dict(
        code="DIG-08",
        dim="D09",
        name="Présence web et réseaux sociaux",
        lens="O",
        weight=5,
        q="Vos canaux numériques (site, réseaux sociaux) sont-ils gérés et mis à jour ?",
        why="Des canaux à jour renforcent la crédibilité de l'entreprise.",
    ),
    dict(
        code="DIG-09",
        dim="D09",
        name="Usage de l'IA et des outils collaboratifs",
        lens="O",
        weight=10,
        q="Utilisez-vous des outils collaboratifs (messagerie partagée, agenda, stockage en ligne) ou l'intelligence artificielle ?",
        why="Ces outils améliorent l'organisation et la productivité de l'équipe.",
    ),
    # --- D10 Risques, contrôle interne & continuité --------------------------------------------------------------
    dict(
        code="RIS-01",
        dim="D10",
        name="Cartographie ou registre des risques",
        lens="O",
        weight=15,
        evidence="RECOMMENDED",
        docs=["REGISTRE_RISQUES"],
        q="Avez-vous listé les principaux risques qui pourraient mettre l'entreprise en difficulté ?",
        why="Identifier les risques est la première étape pour s'en protéger.",
    ),
    dict(
        code="RIS-02",
        dim="D10",
        name="Contrôle interne de base (séparation des tâches, double signature)",
        lens="O",
        weight=20,
        evidence="RECOMMENDED",
        docs=["PROC_CONTROLE_INTERNE"],
        q="Les paiements importants demandent-ils une double validation, et les tâches sensibles sont-elles séparées ?",
        why="Le contrôle interne évite les erreurs et les détournements.",
    ),
    dict(
        code="RIS-03",
        dim="D10",
        name="Gestion de la caisse et prévention de la fraude",
        lens="R",
        weight=15,
        evidence="RECOMMENDED",
        docs=["PROC_CAISSE"],
        q="La caisse est-elle comptée et rapprochée régulièrement ?",
        why="Une caisse non contrôlée est la première source de pertes dans les PME.",
        anchors=[
            "La caisse n'est jamais contrôlée.",
            "Contrôle occasionnel.",
            "Contrôle régulier mais sans trace écrite.",
            "Contrôle quotidien ou hebdomadaire avec feuille de caisse signée.",
            "Contrôle régulier, écarts analysés et procédure écrite appliquée.",
        ],
    ),
    dict(
        code="RIS-04",
        dim="D10",
        name="Assurances adaptées",
        lens="C",
        weight=15,
        evidence="REQUIRED",
        docs=["ATTEST_ASSURANCE"],
        q="L'entreprise est-elle assurée (responsabilité civile, locaux, marchandises, véhicules) ?",
        why="Un sinistre non assuré peut entraîner la fermeture de l'entreprise.",
        anchors=[
            "Aucune assurance.",
            "Une assurance partielle (par exemple véhicule uniquement).",
            "Les principales assurances, sans attestation à jour.",
            "Assurances adaptées avec attestations à jour.",
            "Assurances adaptées, revues chaque année selon l'évolution de l'activité.",
        ],
        hint="Attestations d'assurance",
    ),
    dict(
        code="RIS-05",
        dim="D10",
        name="Plan de continuité d'activité",
        lens="O",
        weight=15,
        evidence="RECOMMENDED",
        docs=["PCA"],
        q="Avez-vous prévu comment continuer l'activité en cas de problème majeur (incendie, panne, absence d'une personne clé) ?",
        why="Un plan de continuité permet de redémarrer vite après un incident.",
    ),
    dict(
        code="RIS-06",
        dim="D10",
        name="Gestion de crise",
        lens="O",
        weight=10,
        q="En cas de crise, savez-vous qui fait quoi et qui contacter ?",
        why="Une crise bien gérée limite les dégâts pour l'entreprise et sa réputation.",
    ),
    dict(
        code="RIS-07",
        dim="D10",
        name="Litiges en cours maîtrisés",
        lens="R",
        weight=10,
        q="L'entreprise a-t-elle des litiges (clients, fournisseurs, salariés, administration) non maîtrisés ?",
        why="Un litige non suivi peut coûter très cher.",
        anchors=[
            "Oui, des litiges importants sans suivi.",
            "Oui, des litiges suivis sans stratégie claire.",
            "Quelques litiges suivis avec un conseil.",
            "Aucun litige significatif.",
            "Aucun litige, et les risques de litige sont prévenus (contrats, procédures).",
        ],
    ),
    # --- D11 Financement & opportunités --------------------------------------------------------------------------
    dict(
        code="FIO-01",
        dim="D11",
        name="Besoin de financement identifié et chiffré",
        lens="O",
        weight=15,
        evidence="RECOMMENDED",
        docs=["PLAN_FINANCEMENT"],
        q="Savez-vous combien il vous faudrait pour vous développer et pour quoi faire ?",
        why="Un besoin chiffré et justifié est la première étape de toute demande de financement.",
    ),
    dict(
        code="FIO-02",
        dim="D11",
        name="Relation bancaire",
        lens="P",
        weight=15,
        q="Quelle est votre relation avec les banques ou les institutions de microfinance ?",
        why="Un bon historique bancaire facilite l'accès au crédit.",
        anchors=[
            "Aucun compte bancaire professionnel.",
            "Un compte, peu utilisé ou avec des incidents.",
            "Un compte utilisé normalement, sans crédit.",
            "Un crédit obtenu et remboursé sans incident.",
            "Plusieurs financements obtenus et une relation de confiance avec la banque.",
        ],
    ),
    dict(
        code="FIO-03",
        dim="D11",
        name="Capacité à présenter un dossier finançable",
        lens="O",
        weight=20,
        q="Pourriez-vous présenter rapidement un dossier de financement complet (états financiers, plan d'affaires, garanties) ?",
        why="Un dossier complet et prêt accélère fortement l'obtention d'un financement.",
    ),
    dict(
        code="FIO-04",
        dim="D11",
        name="Connaissance des dispositifs d'appui",
        lens="O",
        weight=10,
        q="Connaissez-vous et utilisez-vous les dispositifs d'appui aux PME (programmes, fonds de garantie, subventions) ?",
        why="Ces dispositifs peuvent réduire le coût ou le risque de vos projets.",
    ),
    dict(
        code="FIO-05",
        dim="D11",
        name="Accès aux marchés publics",
        lens="P",
        weight=15,
        q="Répondez-vous à des marchés publics ?",
        why="Les marchés publics sont une source importante de chiffre d'affaires pour les PME.",
        anchors=[
            "Jamais.",
            "Nous nous sommes renseignés.",
            "Nous avons déjà répondu sans succès.",
            "Nous avons gagné au moins un marché.",
            "Nous gagnons régulièrement des marchés.",
        ],
    ),
    dict(
        code="FIO-06",
        dim="D11",
        name="Export ou marchés régionaux",
        lens="P",
        weight=10,
        q="Vendez-vous en dehors de la Côte d'Ivoire ?",
        why="Les marchés régionaux offrent des relais de croissance.",
        anchors=[
            "Non, et ce n'est pas envisagé.",
            "Non, mais c'est envisagé.",
            "Des ventes ponctuelles.",
            "Des ventes régulières dans un pays.",
            "Des ventes régulières dans plusieurs pays.",
        ],
    ),
    dict(
        code="FIO-07",
        dim="D11",
        name="Partenariats et investisseurs",
        lens="P",
        weight=15,
        q="Avez-vous des partenariats stratégiques ou des investisseurs ?",
        why="Les partenaires apportent des ressources, des marchés et de la crédibilité.",
        anchors=[
            "Aucun.",
            "Des contacts sans suite.",
            "Un partenariat en discussion.",
            "Un partenariat actif.",
            "Plusieurs partenariats actifs ou un investisseur au capital.",
        ],
    ),
    # --- D12 Innovation & croissance -----------------------------------------------------------------------------
    dict(
        code="INN-01",
        dim="D12",
        name="Nouveaux produits ou services lancés (3 dernières années)",
        lens="P",
        weight=20,
        q="Avez-vous lancé de nouveaux produits ou services au cours des 3 dernières années ?",
        why="Le renouvellement de l'offre permet de rester compétitif.",
        anchors=[
            "Aucun.",
            "Un lancement, sans succès.",
            "Un lancement réussi.",
            "Plusieurs lancements réussis.",
            "Des lancements réguliers qui représentent une part importante des ventes.",
        ],
    ),
    dict(
        code="INN-02",
        dim="D12",
        name="Nouveaux marchés ou segments conquis",
        lens="P",
        weight=15,
        q="Avez-vous conquis de nouveaux marchés ou types de clients récemment ?",
        why="Conquérir de nouveaux marchés réduit la dépendance aux clients actuels.",
        anchors=[
            "Aucun.",
            "Des tentatives sans résultat.",
            "Un nouveau marché.",
            "Plusieurs nouveaux marchés.",
            "Une conquête régulière et planifiée de nouveaux marchés.",
        ],
    ),
    dict(
        code="INN-03",
        dim="D12",
        name="Démarche d'innovation (veille, R&D, amélioration continue)",
        lens="O",
        weight=15,
        q="Faites-vous de la veille, de la recherche ou de l'amélioration continue de vos produits et méthodes ?",
        why="L'innovation régulière est un avantage face à la concurrence.",
    ),
    dict(
        code="INN-04",
        dim="D12",
        name="Propriété intellectuelle (marques, brevets)",
        lens="C",
        weight=15,
        evidence="RECOMMENDED",
        docs=["CERTIFICAT_PI"],
        q="Avez-vous protégé votre marque ou vos inventions (dépôt à l'OAPI) ?",
        why="Protéger sa marque empêche les concurrents de la copier.",
    ),
    dict(
        code="INN-05",
        dim="D12",
        name="Partenariats d'innovation",
        lens="O",
        weight=10,
        q="Travaillez-vous avec des universités, des incubateurs ou de grandes entreprises pour innover ?",
        why="Les partenariats d'innovation donnent accès à des compétences et à des financements.",
    ),
    dict(
        code="INN-06",
        dim="D12",
        name="Capacité d'expansion et de passage à l'échelle",
        lens="O",
        weight=25,
        q="Votre entreprise pourrait-elle doubler son activité sans désorganisation (processus, équipe, financement) ?",
        why="La capacité à grandir sans se désorganiser est la clé d'une croissance durable.",
    ),
]

# Questions de profil (pilotent l'adaptation du questionnaire, Document 5, § 6).
PROFILE_QUESTIONS = [
    dict(
        code="PRO-EFF",
        feeds="profile.headcount",
        type="NUMBER",
        audience="LES_DEUX",
        q="Combien de salariés (hors dirigeant) compte l'entreprise aujourd'hui ?",
        why="L'effectif détermine notamment les obligations sociales qui s'appliquent.",
    ),
    dict(
        code="PRO-FAM",
        feeds="profile.is_family_business",
        type="BOOLEAN",
        audience="LES_DEUX",
        q="S'agit-il d'une entreprise familiale (plusieurs membres d'une même famille au capital ou à la direction) ?",
        why="Certaines questions de gouvernance ne concernent que les entreprises familiales.",
    ),
    dict(
        code="PRO-STK",
        feeds="profile.has_stock",
        type="BOOLEAN",
        audience="LES_DEUX",
        q="Votre activité utilise-t-elle des stocks (marchandises, matières premières) ?",
        why="La gestion des stocks n'est évaluée que si elle vous concerne.",
    ),
    dict(
        code="PRO-PRD",
        feeds="profile.has_production",
        type="BOOLEAN",
        audience="LES_DEUX",
        q="Votre activité comprend-elle de la production ou de la transformation (atelier, usine, équipements) ?",
        why="La maintenance des équipements n'est évaluée que si elle vous concerne.",
    ),
]

# Données financières déclaratives (alimentent les indicateurs ; le dernier exercice clos).
FINANCIAL_INPUTS = [
    ("ca_n", "AMOUNT", "Chiffre d'affaires du dernier exercice (FCFA)"),
    ("ca_n1", "AMOUNT", "Chiffre d'affaires de l'exercice précédent (FCFA)"),
    ("ebe", "AMOUNT", "Excédent brut d'exploitation du dernier exercice (FCFA)"),
    ("resultat_net", "AMOUNT", "Résultat net du dernier exercice (FCFA, négatif en cas de perte)"),
    ("dotations", "AMOUNT", "Dotations aux amortissements et provisions (FCFA)"),
    ("capitaux_propres", "AMOUNT", "Capitaux propres (FCFA)"),
    ("total_passif", "AMOUNT", "Total du bilan (FCFA)"),
    ("dettes_financieres", "AMOUNT", "Dettes financières : emprunts bancaires et assimilés (FCFA)"),
    ("actif_circulant", "AMOUNT", "Actif circulant, trésorerie comprise (FCFA)"),
    ("passif_circulant", "AMOUNT", "Passif circulant, trésorerie passive comprise (FCFA)"),
    ("creances_clients", "AMOUNT", "Créances clients (FCFA)"),
    ("part_client_1", "PERCENT", "Part du premier client dans le chiffre d'affaires (%)"),
    ("part_clients_top5", "PERCENT", "Part des 5 premiers clients dans le chiffre d'affaires (%)"),
    ("part_fournisseur_1", "PERCENT", "Part du premier fournisseur dans les achats (%)"),
]


def _bands(*thresholds_and_points):
    """(seuil, points)… puis points final : bandes évaluées dans l'ordre, ``value < seuil``."""
    labels = {0: "Critique", 25: "Faible", 50: "Acceptable", 75: "Bon", 100: "Excellent"}
    *pairs, last = thresholds_and_points
    bands = [{"upto": upto, "points": points, "label": labels[points]} for upto, points in pairs]
    bands.append({"upto": None, "points": last, "label": labels[last]})
    return bands


# (code, critère, nom, formule, formule en clair, unité, bandes, poids) — Document 6, § 7.1 (seuils indicatifs).
METRICS = [
    (
        "MARGE_NETTE",
        "FIN-06",
        "Rentabilité nette",
        "resultat_net / ca_n",
        "Résultat net / Chiffre d'affaires",
        "PERCENT",
        _bands((0, 0), (0.02, 25), (0.05, 50), (0.10, 75), 100),
        1,
    ),
    (
        "TAUX_EBE",
        "FIN-06",
        "Taux d'EBE",
        "ebe / ca_n",
        "EBE / Chiffre d'affaires",
        "PERCENT",
        _bands((0, 0), (0.05, 25), (0.10, 50), (0.20, 75), 100),
        1,
    ),
    (
        "CA_CROISSANCE",
        "FIN-07",
        "Croissance du chiffre d'affaires",
        "(ca_n - ca_n1) / ca_n1",
        "(CA N − CA N-1) / CA N-1",
        "PERCENT",
        _bands((-0.10, 0), (0, 25), (0.05, 50), (0.15, 75), 100),
        1,
    ),
    (
        "AUTONOMIE",
        "FIN-08",
        "Autonomie financière",
        "capitaux_propres / total_passif",
        "Capitaux propres / Total du bilan",
        "PERCENT",
        _bands((0.10, 0), (0.20, 25), (0.35, 50), (0.50, 75), 100),
        1,
    ),
    (
        "ENDETTEMENT",
        "FIN-08",
        "Taux d'endettement (gearing)",
        "dettes_financieres / capitaux_propres",
        "Dettes financières / Capitaux propres",
        "RATIO",
        _bands((0, 0), (0.5, 100), (1, 75), (2, 50), (3, 25), 0),
        1,
    ),
    (
        "CAF",
        None,
        "Capacité d'autofinancement (méthode simplifiée)",
        "resultat_net + dotations",
        "Résultat net + Dotations aux amortissements et provisions",
        "AMOUNT",
        [],
        0,
    ),
    (
        "CAP_REMB",
        "FIN-10",
        "Capacité de remboursement",
        "dettes_financieres / (resultat_net + dotations)",
        "Dettes financières / CAF (en années)",
        "YEARS",
        _bands((0, 0), (1, 100), (3, 75), (5, 50), (7, 25), 0),
        1,
    ),
    (
        "LIQ_GEN",
        "FIN-09",
        "Liquidité générale",
        "actif_circulant / passif_circulant",
        "Actif circulant / Passif circulant",
        "RATIO",
        _bands((0.8, 0), (1, 25), (1.2, 50), (1.5, 75), 100),
        1,
    ),
    (
        "DSO",
        "FIN-09",
        "Délai de paiement clients",
        "creances_clients / ca_n * 360",
        "Créances clients / CA × 360 (CA HT, approximation)",
        "DAYS",
        _bands((30, 100), (60, 75), (90, 50), (120, 25), 0),
        1,
    ),
    (
        "CONC_CLIENT_1",
        "FIN-11",
        "Concentration du premier client",
        "part_client_1 / 100",
        "CA du 1er client / CA total",
        "PERCENT",
        _bands((0.10, 100), (0.20, 75), (0.35, 50), (0.50, 25), 0),
        1,
    ),
    (
        "CONC_CLIENT_5",
        "FIN-11",
        "Concentration des 5 premiers clients",
        "part_clients_top5 / 100",
        "CA des 5 premiers clients / CA total",
        "PERCENT",
        _bands((0.25, 100), (0.40, 75), (0.60, 50), (0.80, 25), 0),
        1,
    ),
    (
        "CONC_FOURN_1",
        "FIN-11",
        "Dépendance au premier fournisseur",
        "part_fournisseur_1 / 100",
        "Achats au 1er fournisseur / Achats totaux",
        "PERCENT",
        _bands((0.15, 100), (0.30, 75), (0.45, 50), (0.60, 25), 0),
        1,
    ),
    (
        "DEP_CLIENT_1",
        "COM-08",
        "Dépendance au premier client",
        "part_client_1 / 100",
        "CA du 1er client / CA total",
        "PERCENT",
        _bands((0.10, 100), (0.20, 75), (0.35, 50), (0.50, 25), 0),
        1,
    ),
]

# Configuration du moteur pour cette version (Document 6) — données, pas code.
SETTINGS = {
    "engine": {
        "provisional_coverage": 0.70,
        "non_evaluable_coverage": 0.40,
        "not_applicable_exclusion": 0.70,
        "declarative_validity_days": 365,
    },
    "maturity_levels": [
        {
            "level": 1,
            "label": "Fragile",
            "min": 0,
            "message": "Les bases de votre entreprise doivent être consolidées en priorité.",
        },
        {
            "level": 2,
            "label": "En structuration",
            "min": 35,
            "message": "Vous avez commencé à vous organiser ; il reste des fondations à poser.",
        },
        {
            "level": 3,
            "label": "Structurée",
            "min": 55,
            "message": "Votre entreprise est organisée ; place à l'optimisation.",
        },
        {"level": 4, "label": "Maîtrisée", "min": 70, "message": "Votre entreprise est bien pilotée et conforme."},
        {
            "level": 5,
            "label": "Prête pour la croissance",
            "min": 85,
            "message": "Vous êtes prête à changer d'échelle : financement, nouveaux marchés.",
        },
    ],
    "gates": {
        "2": {"critical_pillar_min_level": {"pillar": "A", "level": 1}},
        "3": {"critical_min_level": 2, "pillar_dimension_min": {"pillar": "A", "score": 40}},
        "4": {
            "critical_min_level": 3,
            "critical_proven": True,
            "dimension_min": 40,
            "confidence_min": 0.60,
            "no_critical_alert": True,
        },
        "5": {"dimension_min": 55, "ipe_min": 60, "confidence_min": 0.75},
    },
    "confidence": {
        "sources": {
            "DOCUMENT_VERIFIE": 1.0,
            "DOCUMENT_IA": 0.80,
            "DECLARATIF_CORROBORE": 0.60,
            "DECLARATIF": 0.45,
            "INFERE": 0.35,
        },
        "bands": [{"min": 0.75, "label": "Élevée"}, {"min": 0.50, "label": "Moyenne"}, {"min": 0, "label": "Faible"}],
    },
    "quadrants": {"imo_threshold": 55, "ipe_threshold": 60},
    "digital_index": {
        "dimension": "D09",
        "extra_criteria": ["COM-05"],
        "levels": [
            {"min": 0, "label": "Analogique"},
            {"min": 20, "label": "Équipé"},
            {"min": 40, "label": "Connecté"},
            {"min": 60, "label": "Intégré"},
            {"min": 80, "label": "Piloté par la donnée"},
        ],
    },
    # Priorité d'intervention (Document 6, § 6) : première règle vérifiée, sinon P3.
    "priority_rules": [
        {
            "priority": "P1",
            "label": "Urgente",
            "condition": {
                "or": [
                    {">": [{"var": "open_critical_alerts"}, 0]},
                    {">=": [{"var": "risk_index"}, 70]},
                    {"and": [{"<": [{"var": "imo"}, 35]}, {"<=": [{"var": "delta_imo"}, -5]}]},
                ]
            },
        },
        {
            "priority": "P2",
            "label": "Renforcée",
            "condition": {
                "or": [
                    {"<": [{"var": "imo"}, 55]},
                    {">=": [{"var": "risk_index"}, 50]},
                    {">=": [{"var": "overdue_critical_actions"}, 3]},
                    {
                        "and": [
                            {">=": [{"var": "months_since_baseline"}, 6]},
                            {"<": [{"var": "delta_global_since_baseline"}, 2]},
                        ]
                    },
                ]
            },
        },
        {
            "priority": "P4",
            "label": "Veille",
            "condition": {
                "and": [
                    {">=": [{"var": "maturity_level"}, 4]},
                    {"<": [{"var": "risk_index"}, 30]},
                    {"==": [{"var": "open_high_alerts"}, 0]},
                ]
            },
        },
    ],
    "default_priority": {"priority": "P3", "label": "Standard"},
}
