# Generated by Django 5.2.17 on 2026-09-25 14:35

import django.contrib.postgres.indexes
import django.db.models.deletion
import pme360.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalForm',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_company', models.BooleanField(default=True, help_text='Société (statuts, organes sociaux) vs entreprise individuelle.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legal_form',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pme',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=250, verbose_name='raison sociale')),
                ('trade_name', models.CharField(blank=True, max_length=250, verbose_name='sigle ou nom commercial')),
                ('rccm_number', models.CharField(blank=True, max_length=60, verbose_name='n° RCCM')),
                ('ncc', models.CharField(blank=True, max_length=30, verbose_name='n° de compte contribuable')),
                ('cnps_employer_number', models.CharField(blank=True, max_length=30, verbose_name='n° employeur CNPS')),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('commune', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('headcount', models.PositiveIntegerField(blank=True, null=True, verbose_name='effectif déclaré')),
                ('size_category', models.CharField(choices=[('NON_DETERMINEE', 'Non déterminée'), ('MICRO', 'Micro-entreprise'), ('PETITE', 'Petite entreprise'), ('MOYENNE', 'Moyenne entreprise'), ('HORS_PME', 'Hors PME')], default='NON_DETERMINEE', max_length=20)),
                ('lifecycle_status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ONBOARDING', 'Intégration'), ('DIAGNOSTIC_EN_COURS', 'Diagnostic en cours'), ('ACCOMPAGNEMENT_ACTIF', 'Accompagnement actif'), ('SUSPENDU', 'Suspendu'), ('SORTIE', 'Sortie du programme'), ('SUIVI_POST_PROGRAMME', 'Suivi post-programme')], default='PROSPECT', max_length=30)),
                ('onboarding_started_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('DIPLOMEE', 'Diplômée'), ('ABANDON', 'Abandon'), ('REORIENTATION', 'Réorientation')], max_length=20)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('legal_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pmes.legalform')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pme',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='PmeAssignment',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_in_pme', models.CharField(choices=[('CONSEILLER_PRINCIPAL', 'Conseiller principal'), ('EXPERT', 'Expert')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='pmes.pme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pme_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pme_assignment',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PmeEnrollment',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_at', models.DateField()),
                ('exited_at', models.DateField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=200)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='organizations.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='pmes.pme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pme_enrollment',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='PmePerson',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('GERANT', 'Gérant'), ('DG', 'Directeur général'), ('PCA', "Président du conseil d'administration"), ('PRESIDENT', 'Président'), ('ASSOCIE', 'Associé'), ('DIRECTEUR', 'Directeur'), ('CONTACT', 'Contact')], max_length=20)),
                ('share_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Femme'), ('H', 'Homme')], help_text='Facultatif (statistiques).', max_length=1)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, help_text='Facultatif (statistiques).', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='pmes.pme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pme_person',
                'ordering': ['-is_primary_contact', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('REGION', 'Région'), ('DISTRICT_AUTONOME', 'District autonome')], default='REGION', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'region',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pme',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pmes.region'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sector',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pme',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pmes.sector'),
        ),
        migrations.AddConstraint(
            model_name='legalform',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='legal_form_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='pmeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('role_in_pme', 'CONSEILLER_PRINCIPAL')), fields=('pme',), name='pme_one_active_principal_advisor'),
        ),
        migrations.AddConstraint(
            model_name='pmeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('pme', 'user', 'role_in_pme'), name='pme_assignment_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='pmeenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('exited_at__isnull', True)), fields=('pme', 'cohort'), name='pme_enrollment_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='pmeperson',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_contact', True)), fields=('pme',), name='pme_person_one_primary_contact'),
        ),
        migrations.AddConstraint(
            model_name='pmeperson',
            constraint=models.CheckConstraint(condition=models.Q(('share_pct__isnull', True), models.Q(('share_pct__gte', 0), ('share_pct__lte', 100)), _connector='OR'), name='pme_person_share_pct_range'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='region_unique_code'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='sector_unique_code'),
        ),
        migrations.AddIndex(
            model_name='pme',
            index=django.contrib.postgres.indexes.GinIndex(fields=['legal_name'], name='pme_legal_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='pme',
            index=models.Index(fields=['organization', 'lifecycle_status'], name='pme_lifecycle_idx'),
        ),
        migrations.AddConstraint(
            model_name='pme',
            constraint=models.UniqueConstraint(condition=models.Q(('rccm_number', ''), _negated=True), fields=('organization', 'rccm_number'), name='pme_unique_rccm'),
        ),
        migrations.AddConstraint(
            model_name='pme',
            constraint=models.UniqueConstraint(condition=models.Q(('ncc', ''), _negated=True), fields=('organization', 'ncc'), name='pme_unique_ncc'),
        ),
    ]
