# Generated by Django 5.2.17 on 2026-09-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRefresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=60, unique=True)),
                ('refreshed_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'analytics_refresh',
            },
        ),
    ]
