# Generated by Django 5.2.17 on 2026-09-26 16:08

import django.db.models.deletion
import pme360.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationKey',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('wrapped_key', models.TextField(help_text='Clé de données chiffrée par la clé maîtresse (Fernet).')),
                ('master_key_id', models.CharField(help_text='Empreinte de la clé maîtresse ayant enveloppé.', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retirée (lecture seule)')], default='ACTIVE', max_length=8)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_key',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'version'), name='organization_key_unique_version'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('organization',), name='organization_key_one_active')],
            },
        ),
    ]
