"""Catalogue par défaut de l'accompagnement (Document 7, § 3.4 et § 7) : livrables, offres et règles.

Valeurs de départ à valider par GUDE-PME (durées, coûts, niveaux visés) ; chaque organisation les adapte ensuite
sans code. Les règles sont installées ACTIVES en version 1 : une modification crée une nouvelle version.
Variables disponibles dans les conditions : voir ``pme360.plans.rules.variables``.
"""

from __future__ import annotations

# code, titre, catégorie, format, type de document de dépôt, instructions, critères de vérification
DELIVERABLE_TEMPLATES = [
    (
        "LIV-STATUTS",
        "Statuts à jour",
        "Organisation",
        "pdf",
        "STATUTS",
        "Déposez les statuts signés et, s'ils ont changé, la dernière version mise à jour (capital, gérance, siège).",
        ["Signés par les associés", "Cohérents avec le RCCM (dénomination, siège, capital)", "Gérance identifiée"],
    ),
    (
        "LIV-PV-AG",
        "Procès-verbal de la dernière assemblée",
        "Organisation",
        "pdf",
        "PV_AG",
        "Déposez le procès-verbal de la dernière assemblée ou décision des associés, signé.",
        ["Daté de moins de 18 mois", "Signé", "Approbation des comptes mentionnée"],
    ),
    (
        "LIV-CALENDRIER-FISCAL",
        "Calendrier fiscal et déclarations à jour",
        "Finance",
        "pdf",
        "DECL_FISCALE_PERIODIQUE",
        "Listez chaque impôt dû, sa date limite et joignez la dernière déclaration déposée avec son accusé.",
        ["Toutes les déclarations du régime listées", "Dernière déclaration déposée dans le délai"],
    ),
    (
        "LIV-ATTEST-FISC",
        "Attestation de régularité fiscale",
        "Finance",
        "pdf",
        "ATTEST_REGUL_FISC",
        "Demandez l'attestation au centre des impôts après régularisation et déposez-la.",
        ["En cours de validité", "Au nom de l'entreprise"],
    ),
    (
        "LIV-DECL-CNPS",
        "Déclaration CNPS de la période",
        "RH",
        "pdf",
        "DECL_CNPS_PERIODIQUE",
        "Déposez la dernière déclaration CNPS avec la preuve de paiement des cotisations.",
        ["Période la plus récente", "Effectif cohérent avec le registre du personnel", "Paiement joint"],
    ),
    (
        "LIV-CONTRAT-TRAVAIL",
        "Modèle de contrat de travail",
        "RH",
        "docx",
        "CONTRAT_TRAVAIL_ECHANTILLON",
        "Utilisez le modèle : poste, salaire, horaires, date d'embauche. Déposez un contrat signé (données masquées).",
        ["Mentions obligatoires présentes", "Signé par les deux parties", "Données personnelles masquées"],
    ),
    (
        "LIV-TRESO",
        "Tableau de trésorerie mensuel",
        "Finance",
        "xlsx",
        "TABLEAU_TRESORERIE",
        "Chaque mois, notez le solde de départ, les encaissements, les décaissements et le solde de fin. Remplissez "
        "les 3 derniers mois puis les 3 prochains (prévision).",
        ["3 mois réalisés", "3 mois prévus", "Soldes rapprochés du relevé bancaire"],
    ),
    (
        "LIV-TABLEAU-BORD",
        "Tableau de bord financier mensuel",
        "Finance",
        "xlsx",
        "TABLEAU_BORD_FIN",
        "Suivez chaque mois : chiffre d'affaires, marge, charges principales, trésorerie. Comparez au mois précédent.",
        ["2 mois consécutifs", "Indicateurs commentés", "Données cohérentes avec la comptabilité"],
    ),
    (
        "LIV-BUDGET",
        "Budget annuel",
        "Finance",
        "xlsx",
        "BUDGET",
        "Estimez mois par mois les ventes et les dépenses de l'année, puis comparez chaque mois au réalisé.",
        ["12 mois", "Hypothèses écrites", "Validé par le dirigeant"],
    ),
    (
        "LIV-BP",
        "Business plan",
        "Stratégie",
        "docx",
        "BUSINESS_PLAN",
        "Décrivez le projet, le marché, l'organisation et les chiffres prévisionnels sur 3 ans (modèle guidé).",
        ["Marché et concurrence décrits", "Prévisionnel sur 3 ans", "Besoin de financement chiffré"],
    ),
    (
        "LIV-PREVISIONNEL",
        "Prévisionnel financier sur 3 ans",
        "Finance",
        "xlsx",
        "PREVISIONNEL",
        "Complétez les onglets ventes, charges, investissements : le compte de résultat se calcule seul.",
        ["Hypothèses de ventes justifiées", "Trésorerie prévisionnelle positive ou besoin identifié"],
    ),
    (
        "LIV-SUIVI-COMMERCIAL",
        "Tableau de suivi commercial (pipeline)",
        "Commercial",
        "xlsx",
        "TABLEAU_SUIVI_COMMERCIAL",
        "Une ligne par prospect ou client : contact, besoin, montant, étape, prochaine action et date.",
        ["Mis à jour depuis moins d'un mois", "Étapes et montants renseignés"],
    ),
    (
        "LIV-PLAN-PROSPECTION",
        "Plan de prospection",
        "Commercial",
        "docx",
        "PLAN_MARKETING",
        "Listez 10 nouveaux clients cibles, comment les contacter et un objectif de chiffre d'affaires par client.",
        ["Cibles nommées", "Objectif de réduction de la part du premier client"],
    ),
    (
        "LIV-PROC-ACHATS",
        "Procédure d'achats",
        "Opérations",
        "docx",
        "PROC_ACHATS",
        "Décrivez qui demande, qui valide, combien de devis sont demandés et comment la réception est contrôlée.",
        ["Seuils de validation fixés", "Au moins 2 devis au-delà du seuil", "Signée par le dirigeant"],
    ),
    (
        "LIV-ORGANIGRAMME",
        "Organigramme",
        "Organisation",
        "pdf",
        "ORGANIGRAMME",
        "Dessinez qui dirige qui : un cadre par poste, avec le nom de la personne. Datez-le.",
        ["Tous les postes présents", "Liens hiérarchiques clairs", "Daté"],
    ),
    (
        "LIV-FICHES-POSTE",
        "Fiches de poste des postes clés",
        "RH",
        "docx",
        "FICHES_POSTE",
        "Pour chaque poste clé : missions, tâches principales, responsable, compétences attendues.",
        ["Au moins les postes clés couverts", "Missions et responsable indiqués"],
    ),
    (
        "LIV-POLITIQUE-SAUVEGARDE",
        "Politique de sauvegarde et test de restauration",
        "Digital",
        "pdf",
        "POLITIQUE_SAUVEGARDE",
        "Indiquez quoi sauvegarder, à quelle fréquence, où, et joignez la preuve d'un test de restauration réussi.",
        ["Fréquence définie", "Copie hors site", "Preuve de restauration datée"],
    ),
    (
        "LIV-POLITIQUE-SI",
        "Politique informatique",
        "Digital",
        "docx",
        "POLITIQUE_SI",
        "Règles simples : mots de passe, mises à jour, antivirus, accès des départs, usage des téléphones.",
        ["Mots de passe et accès couverts", "Diffusée au personnel"],
    ),
    (
        "LIV-PROC-CAISSE",
        "Procédure de caisse et rapprochements",
        "Risques",
        "docx",
        "PROC_CAISSE",
        "Qui tient la caisse, comptage quotidien, pièce pour chaque sortie, rapprochement signé chaque mois.",
        ["Comptage quotidien", "Justificatif de chaque sortie", "1 mois de rapprochements signés"],
    ),
    (
        "LIV-CONTROLE-INTERNE",
        "Procédure de contrôle interne (double signature)",
        "Risques",
        "docx",
        "PROC_CONTROLE_INTERNE",
        "Séparez qui commande, qui paie et qui enregistre ; double signature au-delà d'un montant fixé.",
        ["Séparation des tâches", "Seuil de double signature"],
    ),
    (
        "LIV-PLAN-FINANCEMENT",
        "Plan de financement",
        "Finance",
        "xlsx",
        "PLAN_FINANCEMENT",
        "Listez les besoins (investissements, fonds de roulement) et les ressources (apports, prêts, subventions).",
        ["Besoins et ressources équilibrés", "Sources identifiées"],
    ),
]

# code, titre, dimension, objectif, durée (j), effort, critères visés, niveau visé, livrables, étapes,
# dépendances (offres), coût min, coût max, prestataire, croissance
SUPPORT_OFFERS = [
    dict(
        code="OFF-JUR-DOSSIER",
        title="Complétude du dossier juridique",
        dimension="D01",
        objective="Disposer d'un dossier juridique complet et à jour.",
        duration=30,
        effort=1,
        criteria=["FOR-02", "FOR-04"],
        level=3,
        deliverables=["LIV-STATUTS", "LIV-PV-AG"],
        steps=[
            "Rassembler les pièces existantes",
            "Mettre à jour les statuts si besoin",
            "Tenir et signer le PV annuel",
        ],
        required=["RCCM", "STATUTS", "DFE", "PV_AG"],
    ),
    dict(
        code="OFF-FIS-REGUL",
        title="Régularisation et calendrier fiscal",
        dimension="D02",
        objective="Être à jour de ses déclarations et paiements fiscaux et le prouver.",
        duration=60,
        effort=3,
        criteria=["FIS-02", "FIS-03", "FIS-04"],
        level=3,
        deliverables=["LIV-CALENDRIER-FISCAL", "LIV-ATTEST-FISC"],
        steps=[
            "Faire le point avec le centre des impôts",
            "Déposer les déclarations manquantes",
            "Obtenir l'attestation",
        ],
        required=["DECL_FISCALE_PERIODIQUE", "ATTEST_REGUL_FISC"],
        cost=(0, 300_000),
    ),
    dict(
        code="OFF-SOC-CNPS",
        title="Mise à jour CNPS et dossiers du personnel",
        dimension="D03",
        objective="Déclarer tous les salariés, payer les cotisations à l'échéance et tenir les dossiers du personnel.",
        duration=60,
        effort=3,
        criteria=["SOC-03", "SOC-05"],
        level=3,
        deliverables=["LIV-DECL-CNPS", "LIV-CONTRAT-TRAVAIL"],
        steps=["Recenser les salariés", "Régulariser les déclarations", "Signer des contrats écrits"],
        required=["DECL_CNPS_PERIODIQUE", "PREUVE_PAIEMENT_CNPS"],
    ),
    dict(
        code="OFF-FIN-TRESO",
        title="Tableau de trésorerie",
        dimension="D04",
        objective="Suivre chaque mois l'argent qui entre et qui sort, et anticiper les tensions.",
        duration=30,
        effort=1,
        criteria=["FIN-03"],
        level=3,
        deliverables=["LIV-TRESO"],
        steps=["Récupérer les relevés des 3 derniers mois", "Remplir le modèle", "Faire la prévision à 3 mois"],
        required=["TABLEAU_TRESORERIE"],
    ),
    dict(
        code="OFF-FIN-REPORTING",
        title="Reporting financier mensuel",
        dimension="D04",
        objective="Piloter l'entreprise avec quelques chiffres clés suivis chaque mois.",
        duration=60,
        effort=2,
        criteria=["FIN-04"],
        level=3,
        deliverables=["LIV-TABLEAU-BORD"],
        steps=["Choisir 5 indicateurs", "Remplir le tableau 2 mois de suite", "Commenter les écarts"],
        required=["TABLEAU_BORD_FIN"],
        depends=["OFF-FIN-TRESO"],
    ),
    dict(
        code="OFF-FIN-BUDGET",
        title="Budget annuel et suivi",
        dimension="D04",
        objective="Fixer des objectifs de ventes et de dépenses et les comparer au réalisé.",
        duration=45,
        effort=2,
        criteria=["FIN-05"],
        level=3,
        deliverables=["LIV-BUDGET"],
        steps=["Estimer les ventes", "Estimer les dépenses", "Comparer chaque mois"],
        required=["BUDGET"],
        depends=["OFF-FIN-TRESO"],
    ),
    dict(
        code="OFF-STR-BP",
        title="Élaboration du business plan",
        dimension="D05",
        objective="Formaliser la stratégie et les chiffres sur 3 ans.",
        duration=90,
        effort=4,
        criteria=["STR-01", "STR-04"],
        level=3,
        deliverables=["LIV-BP", "LIV-PREVISIONNEL"],
        steps=["Atelier vision et objectifs", "Étude de marché simple", "Prévisionnel", "Rédaction et validation"],
        required=["BUSINESS_PLAN", "PREVISIONNEL"],
        depends=["OFF-FIN-TRESO"],
        cost=(0, 1_000_000),
    ),
    dict(
        code="OFF-COM-CRM",
        title="Structuration commerciale et suivi des clients",
        dimension="D06",
        objective="Connaître ses clients et suivre chaque opportunité jusqu'à la vente.",
        duration=60,
        effort=2,
        criteria=["COM-01", "COM-02"],
        level=3,
        deliverables=["LIV-SUIVI-COMMERCIAL"],
        steps=["Lister les clients actifs", "Mettre en place le tableau de suivi", "Point commercial hebdomadaire"],
        required=["TABLEAU_SUIVI_COMMERCIAL"],
    ),
    dict(
        code="OFF-COM-DIVERSIF",
        title="Réduire la dépendance au premier client",
        dimension="D06",
        objective="Élargir la base de clients pour que le premier client pèse moins.",
        duration=90,
        effort=3,
        criteria=["COM-08"],
        level=2,
        deliverables=["LIV-PLAN-PROSPECTION"],
        steps=["Identifier 10 cibles", "Préparer l'offre", "Prospecter et suivre"],
        required=["PLAN_MARKETING"],
        depends=["OFF-COM-CRM"],
    ),
    dict(
        code="OFF-OPE-ACHATS",
        title="Procédure d'achats",
        dimension="D07",
        objective="Acheter au meilleur prix avec des règles claires de validation.",
        duration=30,
        effort=1,
        criteria=["OPE-02"],
        level=3,
        deliverables=["LIV-PROC-ACHATS"],
        steps=["Décrire le circuit actuel", "Fixer les seuils", "Signer et diffuser la procédure"],
        required=["PROC_ACHATS"],
    ),
    dict(
        code="OFF-RH-BASE",
        title="Socle RH : organigramme et fiches de poste",
        dimension="D08",
        objective="Clarifier qui fait quoi et sécuriser la gestion du personnel.",
        duration=60,
        effort=2,
        criteria=["RHO-01", "RHO-02"],
        level=3,
        deliverables=["LIV-ORGANIGRAMME", "LIV-FICHES-POSTE"],
        steps=[
            "Dessiner l'organigramme",
            "Rédiger les fiches des postes clés",
            "Valider avec le dirigeant",
            "Diffuser",
        ],
        required=["ORGANIGRAMME", "FICHES_POSTE"],
    ),
    dict(
        code="OFF-DIG-SECU",
        title="Sauvegardes et cybersécurité de base",
        dimension="D09",
        objective="Ne pas perdre ses données et se protéger des attaques courantes.",
        duration=30,
        effort=1,
        criteria=["DIG-04", "DIG-05"],
        level=3,
        deliverables=["LIV-POLITIQUE-SAUVEGARDE", "LIV-POLITIQUE-SI"],
        steps=["Choisir la solution de sauvegarde", "Tester une restauration", "Écrire les règles informatiques"],
        required=["POLITIQUE_SAUVEGARDE", "POLITIQUE_SI"],
    ),
    dict(
        code="OFF-RIS-CI",
        title="Contrôle interne et caisse",
        dimension="D10",
        objective="Protéger l'argent de l'entreprise : séparation des tâches, double signature, caisse contrôlée.",
        duration=45,
        effort=2,
        criteria=["RIS-02", "RIS-03"],
        level=3,
        deliverables=["LIV-PROC-CAISSE", "LIV-CONTROLE-INTERNE"],
        steps=["Cartographier qui fait quoi", "Rédiger les procédures", "Un mois de rapprochements signés"],
        required=["PROC_CAISSE", "PROC_CONTROLE_INTERNE"],
    ),
    dict(
        code="OFF-FIO-DOSSIER",
        title="Préparation d'un dossier de financement",
        dimension="D11",
        objective="Présenter à une banque ou un fonds un dossier complet et crédible.",
        duration=60,
        effort=3,
        criteria=["FIO-01", "FIO-03"],
        level=3,
        deliverables=["LIV-PLAN-FINANCEMENT"],
        steps=["Chiffrer le besoin", "Rassembler les pièces", "Préparer la présentation"],
        required=["PLAN_FINANCEMENT", "ETATS_FIN_SYSCOHADA"],
        depends=["OFF-STR-BP"],
        growth=True,
    ),
]


def _lte(criterion: str, level: int) -> dict:
    return {"<=": [{"var": f"criterion.{criterion}.level"}, level]}


def _any_lte(criteria: list[str], level: int) -> dict:
    return {"or": [_lte(c, level) for c in criteria]}


# code, nom, condition, offre, problème, justification (gabarit {{variable}})
RECOMMENDATION_RULES = [
    (
        "R-JUR-001",
        "Dossier juridique incomplet",
        _any_lte(["FOR-02", "FOR-04"], 2),
        "OFF-JUR-DOSSIER",
        "Dossier juridique incomplet ou non à jour",
        "Formalisation à {{dimension.D01.score}}/100 : statuts (FOR-02 niveau {{criterion.FOR-02.level}}) ou "
        "décisions d'associés (FOR-04 niveau {{criterion.FOR-04.level}}) à régulariser.",
    ),
    (
        "R-FIS-001",
        "Déclarations ou paiements fiscaux à régulariser",
        _any_lte(["FIS-02", "FIS-03", "FIS-04"], 2),
        "OFF-FIS-REGUL",
        "Situation fiscale non à jour ou non prouvée",
        "Déclarations (FIS-02 niveau {{criterion.FIS-02.level}}), paiements (FIS-03 niveau "
        "{{criterion.FIS-03.level}}) et attestation de régularité (FIS-04 niveau {{criterion.FIS-04.level}}).",
    ),
    (
        "R-SOC-001",
        "Cotisations CNPS non à jour ou non prouvées",
        {"or": [_lte("SOC-03", 2), {"==": [{"var": "criterion.SOC-03.capped"}, True]}]},
        "OFF-SOC-CNPS",
        "Déclarations CNPS non à jour ou non prouvées",
        "CNPS / Social à {{dimension.D03.score}}/100 ; déclarations et cotisations (SOC-03) au niveau "
        "{{criterion.SOC-03.level}}, sans preuve vérifiée suffisante.",
    ),
    (
        "R-FIN-001",
        "Trésorerie non suivie",
        _lte("FIN-03", 2),
        "OFF-FIN-TRESO",
        "Absence de suivi régulier de la trésorerie",
        "Le suivi de trésorerie (FIN-03) est au niveau {{criterion.FIN-03.level}} : les tensions de trésorerie ne "
        "sont pas anticipées.",
    ),
    (
        "R-FIN-002",
        "Reporting financier absent",
        {"and": [{"<": [{"var": "dimension.D04.score"}, 60]}, _lte("FIN-04", 1)]},
        "OFF-FIN-REPORTING",
        "Aucun reporting de gestion périodique",
        "Le score Finance est de {{dimension.D04.score}}/100 et aucun reporting périodique n'existe (FIN-04 "
        "niveau {{criterion.FIN-04.level}}).",
    ),
    (
        "R-FIN-003",
        "Pas de budget",
        _lte("FIN-05", 1),
        "OFF-FIN-BUDGET",
        "Pas de budget ni de prévisions",
        "Budget et prévisions (FIN-05) au niveau {{criterion.FIN-05.level}}.",
    ),
    (
        "R-STR-001",
        "Stratégie non formalisée",
        _any_lte(["STR-01", "STR-04"], 1),
        "OFF-STR-BP",
        "Vision et plan d'affaires non formalisés",
        "Vision (STR-01 niveau {{criterion.STR-01.level}}) et plan d'affaires (STR-04 niveau "
        "{{criterion.STR-04.level}}) à formaliser.",
    ),
    (
        "R-COM-001",
        "Suivi commercial faible",
        _any_lte(["COM-01", "COM-02"], 2),
        "OFF-COM-CRM",
        "Clients et opportunités non suivis",
        "Portefeuille clients (COM-01 niveau {{criterion.COM-01.level}}) et pipeline (COM-02 niveau "
        "{{criterion.COM-02.level}}) peu structurés.",
    ),
    (
        "R-COM-002",
        "Forte dépendance commerciale",
        _lte("COM-08", 1),
        "OFF-COM-DIVERSIF",
        "Dépendance forte au premier client",
        "La dépendance commerciale (COM-08) est au niveau {{criterion.COM-08.level}} : la perte du premier client "
        "mettrait l'activité en danger.",
    ),
    (
        "R-OPE-001",
        "Achats non encadrés",
        _lte("OPE-02", 2),
        "OFF-OPE-ACHATS",
        "Achats sans procédure",
        "Gestion des achats (OPE-02) au niveau {{criterion.OPE-02.level}}.",
    ),
    (
        "R-RHO-001",
        "Organisation RH non formalisée",
        _any_lte(["RHO-01", "RHO-02"], 2),
        "OFF-RH-BASE",
        "Absence d'organigramme ou de fiches de poste",
        "RH & organisation à {{dimension.D08.score}}/100 : organigramme (RHO-01 niveau {{criterion.RHO-01.level}}) "
        "et fiches de poste (RHO-02 niveau {{criterion.RHO-02.level}}).",
    ),
    (
        "R-DIG-001",
        "Sauvegardes et sécurité insuffisantes",
        _any_lte(["DIG-04", "DIG-05"], 2),
        "OFF-DIG-SECU",
        "Données mal protégées",
        "Sauvegardes (DIG-04 niveau {{criterion.DIG-04.level}}) et cybersécurité (DIG-05 niveau "
        "{{criterion.DIG-05.level}}).",
    ),
    (
        "R-RIS-001",
        "Contrôle interne faible",
        _any_lte(["RIS-02", "RIS-03"], 2),
        "OFF-RIS-CI",
        "Caisse et paiements insuffisamment contrôlés",
        "Contrôle interne (RIS-02 niveau {{criterion.RIS-02.level}}) et caisse (RIS-03 niveau "
        "{{criterion.RIS-03.level}}) ; exposition au risque {{risk_index}}/100.",
    ),
    (
        "R-FIO-001",
        "Dossier de financement à préparer",
        {"and": [_lte("FIO-03", 2), {">=": [{"var": "maturity_level"}, 3]}]},
        "OFF-FIO-DOSSIER",
        "Pas de dossier finançable prêt",
        "Niveau de maturité {{maturity_level}} atteint : la PME peut préparer un dossier de financement (FIO-03 "
        "niveau {{criterion.FIO-03.level}}).",
    ),
]

# Paramètres de priorisation (Document 6, § 9) : modifiables par organisation (``settings.plan_priority``).
PRIORITY_SETTINGS = {
    "weights": {"impact": 0.40, "urgency": 0.30, "risk": 0.30},
    "effort_factor": {"1": 1.00, "2": 0.95, "3": 0.85, "4": 0.75, "5": 0.65},
    # Bornes des quintiles d'impact : points de score global gagnables (≥ borne → note).
    "impact_bounds": [0.5, 1.0, 2.0, 3.5],
    "horizons": {"urgent": 70, "structuring": 50, "consolidation": 35},
    "capacity": 5,
}
