# Generated by Django 5.2.17 on 2026-09-26 04:43

import django.db.models.deletion
import pme360.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostic', '0002_security'),
        ('organizations', '0002_rls'),
        ('pmes', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DIAGNOSTIC', 'Rapport de diagnostic'), ('PORTEFEUILLE', 'Rapport de portefeuille')], max_length=14)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=250)),
                ('period', models.CharField(blank=True, max_length=60)),
                ('template_version', models.CharField(max_length=20)),
                ('data_snapshot', models.JSONField(help_text='Données figées au moment de la génération.')),
                ('storage_key', models.CharField(max_length=300)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('engine', models.CharField(help_text='Moteur de rendu PDF utilisé.', max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('generated_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='diagnostic.diagnostic')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('pme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pmes.pme')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report',
                'ordering': ['-generated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('type', 'DIAGNOSTIC')), fields=('diagnostic', 'version'), name='report_diagnostic_version')],
            },
        ),
    ]
