# Generated by Django 5.2.17 on 2026-09-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='scope',
            field=models.JSONField(blank=True, default=dict, help_text="Périmètre d'un rapport de portefeuille (PME incluses)."),
        ),
    ]
