# Generated by Django 5.2.17 on 2026-09-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('DIAGNOSTIC', 'Rapport de diagnostic'), ('PORTEFEUILLE', 'Rapport de portefeuille'), ('SUIVI', 'Rapport de suivi'), ('CONFORMITE', 'Rapport de conformité'), ('ANNUEL', 'Rapport annuel')], max_length=14),
        ),
    ]
