/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Journal d'audit de l'organisation active (lecture seule). */
        get: operations["audit_logs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Recalcule la chaîne de hash du journal de l'organisation (détection d'altération). */
        get: operations["audit_logs_verify_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Point d'entrée d'authentification : anonyme autorisé, CSRF vérifié même sans session, débit limité. */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Point d'entrée d'authentification : anonyme autorisé, CSRF vérifié même sans session, débit limité. */
        post: operations["auth_mfa_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Point d'entrée d'authentification : anonyme autorisé, CSRF vérifié même sans session, débit limité. */
        post: operations["auth_mfa_setup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Point d'entrée d'authentification : anonyme autorisé, CSRF vérifié même sans session, débit limité. */
        post: operations["auth_mfa_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Point d'entrée d'authentification : anonyme autorisé, CSRF vérifié même sans session, débit limité. */
        post: operations["auth_otp_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Point d'entrée d'authentification : anonyme autorisé, CSRF vérifié même sans session, débit limité. */
        post: operations["auth_otp_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Point d'entrée d'authentification : anonyme autorisé, CSRF vérifié même sans session, débit limité. */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Point d'entrée d'authentification : anonyme autorisé, CSRF vérifié même sans session, débit limité. */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/switch-organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_switch_organization_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/advisor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description « Ma journée » du conseiller : son portefeuille (périmètre) et sa file de travail. */
        get: operations["dashboards_advisor_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/pme/{pme_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Accueil du portail PME (Document 9, § 2) : les 4 questions, avec les données disponibles en phase 1. */
        get: operations["dashboards_pme_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboards/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Vue d'ensemble programme / direction (Document 9, § 4.1) — indicateurs disponibles en phase 1. */
        get: operations["dashboards_portfolio_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memberships/{membership_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["memberships_revoke_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Organisation active de l'utilisateur. */
        get: operations["organization_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Organisation active de l'utilisateur. */
        patch: operations["organization_partial_update"];
        trace?: never;
    };
    "/api/v1/platform/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Administration plateforme (SUPER_ADMIN) : création des tenants, sans accès aux contenus métier. */
        get: operations["platform_organizations_list"];
        put?: never;
        /** @description Administration plateforme (SUPER_ADMIN) : création des tenants, sans accès aux contenus métier. */
        post: operations["platform_organizations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pmes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description PME du périmètre de l'utilisateur (rôle + périmètre, Document 1, § 6). */
        get: operations["pmes_list"];
        put?: never;
        /** @description PME du périmètre de l'utilisateur (rôle + périmètre, Document 1, § 6). */
        post: operations["pmes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pmes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description PME du périmètre de l'utilisateur (rôle + périmètre, Document 1, § 6). */
        get: operations["pmes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description PME du périmètre de l'utilisateur (rôle + périmètre, Document 1, § 6). */
        patch: operations["pmes_partial_update"];
        trace?: never;
    };
    "/api/v1/pmes/{id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description PME du périmètre de l'utilisateur (rôle + périmètre, Document 1, § 6). */
        post: operations["pmes_assignments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pmes/{id}/assignments/{assignment_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description PME du périmètre de l'utilisateur (rôle + périmètre, Document 1, § 6). */
        post: operations["pmes_assignments_end_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pmes/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description PME du périmètre de l'utilisateur (rôle + périmètre, Document 1, § 6). */
        get: operations["pmes_timeline_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pmes/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description PME du périmètre de l'utilisateur (rôle + périmètre, Document 1, § 6). */
        post: operations["pmes_transition_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pmes/{pme_pk}/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Dirigeants, associés et contacts d'une PME. */
        get: operations["pmes_persons_list"];
        put?: never;
        /** @description Dirigeants, associés et contacts d'une PME. */
        post: operations["pmes_persons_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pmes/{pme_pk}/persons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Dirigeants, associés et contacts d'une PME. */
        get: operations["pmes_persons_retrieve"];
        put?: never;
        post?: never;
        /** @description Dirigeants, associés et contacts d'une PME. */
        delete: operations["pmes_persons_destroy"];
        options?: never;
        head?: never;
        /** @description Dirigeants, associés et contacts d'une PME. */
        patch: operations["pmes_persons_partial_update"];
        trace?: never;
    };
    "/api/v1/pmes/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description PME du périmètre de l'utilisateur (rôle + périmètre, Document 1, § 6). */
        get: operations["pmes_duplicates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programmes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["programmes_list"];
        put?: never;
        post: operations["programmes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/programmes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["programmes_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["programmes_partial_update"];
        trace?: never;
    };
    "/api/v1/programmes/{id}/cohorts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["programmes_cohorts_list"];
        put?: never;
        post: operations["programmes_cohorts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ref/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Nomenclatures de l'organisation (secteurs, formes juridiques, régions). */
        get: operations["ref_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["roles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Utilisateurs de l'organisation active et leurs appartenances. */
        get: operations["users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/advisors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Utilisateurs pouvant suivre une PME (conseillers, experts, responsables). */
        get: operations["users_advisors_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Invitation : ADMIN_ORG (tout rôle) ou dirigeant de PME (collaborateurs de sa PME) ; contrôle dans le service. */
        post: operations["users_invite_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `USER` - Utilisateur
         *     * `SYSTEM` - Système
         *     * `AI` - IA
         * @enum {string}
         */
        ActorTypeEnum: "USER" | "SYSTEM" | "AI";
        AdvisorSummary: {
            /** Format: uuid */
            id: string;
            full_name: string;
        };
        AssignedUser: {
            /** Format: uuid */
            id: string;
            full_name: string;
            /** Format: email */
            email: string;
        };
        Assignment: {
            /** Format: uuid */
            readonly id: string;
            readonly user: components["schemas"]["AssignedUser"];
            readonly role_in_pme: components["schemas"]["RoleInPmeEnum"];
            /** Format: date */
            readonly start_date: string;
            /** Format: date */
            readonly end_date: string | null;
        };
        AssignmentCreateRequest: {
            /** Format: uuid */
            user_id: string;
            role_in_pme: components["schemas"]["RoleInPmeEnum"];
        };
        AuditLog: {
            readonly id: number;
            /** Format: date-time */
            at: string;
            action: string;
            readonly label: string;
            /** Format: uuid */
            actor?: string | null;
            readonly actor_name: string | null;
            actor_type: components["schemas"]["ActorTypeEnum"];
            entity_type?: string;
            entity_id?: string;
            /** Format: uuid */
            pme_id?: string | null;
            before?: unknown;
            after?: unknown;
            ip?: string | null;
            request_id?: string;
            hash: string;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        ChainVerification: {
            valid: boolean;
            entries_checked: number;
            first_invalid_id: number | null;
        };
        CodeRequest: {
            code: string;
        };
        Cohort: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly programme: string;
            name: string;
            /** Format: date */
            start_date?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        CohortRequest: {
            name: string;
            /** Format: date */
            start_date?: string | null;
        };
        Duplicate: {
            /** Format: uuid */
            id: string;
            legal_name: string;
            rccm_number: string;
            reasons: components["schemas"]["ReasonsEnum"][];
            /** Format: double */
            similarity?: number;
            accessible: boolean;
        };
        EnrolledCohort: {
            /** Format: uuid */
            id: string;
            name: string;
            programme: string;
        };
        Enrollment: {
            /** Format: uuid */
            readonly id: string;
            readonly cohort: components["schemas"]["EnrolledCohort"];
            /** Format: date */
            readonly enrolled_at: string;
            /** Format: date */
            readonly exited_at: string | null;
            readonly exit_reason: string;
        };
        /**
         * @description * `DIPLOMEE` - Diplômée
         *     * `ABANDON` - Abandon
         *     * `REORIENTATION` - Réorientation
         * @enum {string}
         */
        ExitReasonEnum: "DIPLOMEE" | "ABANDON" | "REORIENTATION";
        /**
         * @description * `F` - Femme
         *     * `H` - Homme
         * @enum {string}
         */
        GenderEnum: "F" | "H";
        Health: {
            status: string;
        };
        InviteRequest: {
            /** Format: email */
            email: string;
            full_name: string;
            /** @default  */
            phone: string;
            role: string;
            scope?: components["schemas"]["ScopeEnum"];
            /** Format: uuid */
            scope_ref_id?: string | null;
        };
        /**
         * @description * `PROSPECT` - Prospect
         *     * `ONBOARDING` - Intégration
         *     * `DIAGNOSTIC_EN_COURS` - Diagnostic en cours
         *     * `ACCOMPAGNEMENT_ACTIF` - Accompagnement actif
         *     * `SUSPENDU` - Suspendu
         *     * `SORTIE` - Sortie du programme
         *     * `SUIVI_POST_PROGRAMME` - Suivi post-programme
         * @enum {string}
         */
        LifecycleStatusEnum: "PROSPECT" | "ONBOARDING" | "DIAGNOSTIC_EN_COURS" | "ACCOMPAGNEMENT_ACTIF" | "SUSPENDU" | "SORTIE" | "SUIVI_POST_PROGRAMME";
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginStatus: {
            status: components["schemas"]["LoginStatusEnum"];
        };
        /**
         * @description * `ok` - ok
         *     * `mfa_required` - mfa_required
         *     * `mfa_setup_required` - mfa_setup_required
         * @enum {string}
         */
        LoginStatusEnum: "ok" | "mfa_required" | "mfa_setup_required";
        Me: {
            user: components["schemas"]["MeUser"];
            organization: components["schemas"]["MeOrganization"] | null;
            memberships: components["schemas"]["MeMembership"][];
            permissions: string[];
            roles: string[];
            portal: components["schemas"]["PortalEnum"];
            pme_ids: string[];
        };
        MeMembership: {
            /** Format: uuid */
            organization_id: string;
            organization_name: string;
            role: string;
            role_label: string;
            scope: string;
            /** Format: uuid */
            scope_ref_id: string | null;
        };
        MeOrganization: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            branding: {
                [key: string]: unknown;
            };
        };
        MeUser: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            full_name: string;
            phone?: string;
            locale?: string;
            mfa_enabled?: boolean;
            is_platform_admin?: boolean;
        };
        Membership: {
            /** Format: uuid */
            readonly id: string;
            readonly role: string;
            readonly role_label: string;
            scope: components["schemas"]["ScopeEnum"];
            /**
             * Format: uuid
             * @description Programme ou PME selon le périmètre.
             */
            scope_ref_id?: string | null;
            /** Format: date */
            valid_from?: string;
            /** Format: date */
            valid_to?: string | null;
            is_active?: boolean;
        };
        MfaSetup: {
            secret: string;
            otpauth_uri: string;
        };
        Organization: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            readonly slug: string;
            readonly type: components["schemas"]["TypeEnum"];
            readonly country: string;
            branding?: unknown;
            readonly settings: {
                [key: string]: unknown;
            };
            ai_external_allowed?: boolean;
            readonly status: components["schemas"]["OrganizationStatusEnum"];
        };
        /** @description Utilisateur vu depuis une organisation : ses seules appartenances dans CETTE organisation. */
        OrganizationMember: {
            /** Format: uuid */
            readonly id: string;
            full_name: string;
            /** Format: email */
            email: string;
            phone?: string;
            is_active?: boolean;
            mfa_enabled?: boolean;
            /**
             * Dernière connexion
             * Format: date-time
             */
            last_login?: string | null;
            readonly memberships: components["schemas"]["Membership"][];
        };
        /**
         * @description * `ACTIVE` - Active
         *     * `SUSPENDUE` - Suspendue
         * @enum {string}
         */
        OrganizationStatusEnum: "ACTIVE" | "SUSPENDUE";
        OtpRequestRequest: {
            /** Format: email */
            email: string;
        };
        OtpVerifyRequest: {
            /** Format: email */
            email: string;
            code: string;
            /** @default false */
            trusted_device: boolean;
        };
        PaginatedPmeListList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["PmeList"][];
        };
        PasswordResetConfirmRequest: {
            uid: string;
            token: string;
            new_password: string;
        };
        PasswordResetRequestRequest: {
            /** Format: email */
            email: string;
        };
        PatchedOrganizationUpdateRequest: {
            name?: string;
            branding?: unknown;
            settings?: {
                [key: string]: unknown;
            };
            ai_external_allowed?: boolean;
        };
        PatchedPersonRequest: {
            full_name?: string;
            role?: components["schemas"]["RoleEnum"];
            /** Format: decimal */
            share_pct?: string | null;
            is_primary_contact?: boolean;
            phone?: string;
            email?: string;
            /**
             * @description Facultatif (statistiques).
             *
             *     * `F` - Femme
             *     * `H` - Homme
             */
            gender?: components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"];
            /** @description Facultatif (statistiques). */
            birth_year?: number | null;
        };
        PatchedPmeRequest: {
            /** Raison sociale */
            legal_name?: string;
            /** Sigle ou nom commercial */
            trade_name?: string;
            /** Format: uuid */
            legal_form?: string | null;
            /** N° RCCM */
            rccm_number?: string;
            /** N° de compte contribuable */
            ncc?: string;
            /** N° employeur CNPS */
            cnps_employer_number?: string;
            /** Format: date */
            creation_date?: string | null;
            /** Format: uuid */
            sector?: string | null;
            /** Format: uuid */
            region?: string | null;
            commune?: string;
            address?: string;
            phone?: string;
            email?: string;
            website?: string;
            /** Effectif déclaré */
            headcount?: number | null;
            size_category?: components["schemas"]["SizeCategoryEnum"];
        };
        PatchedProgrammeRequest: {
            name?: string;
            description?: string;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            funder?: string;
            objectives?: unknown;
        };
        Person: {
            /** Format: uuid */
            readonly id: string;
            full_name: string;
            role: components["schemas"]["RoleEnum"];
            /** Format: decimal */
            share_pct?: string | null;
            is_primary_contact?: boolean;
            phone?: string;
            email?: string;
            /**
             * @description Facultatif (statistiques).
             *
             *     * `F` - Femme
             *     * `H` - Homme
             */
            gender?: components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"];
            /** @description Facultatif (statistiques). */
            birth_year?: number | null;
        };
        PersonRequest: {
            full_name: string;
            role: components["schemas"]["RoleEnum"];
            /** Format: decimal */
            share_pct?: string | null;
            is_primary_contact?: boolean;
            phone?: string;
            email?: string;
            /**
             * @description Facultatif (statistiques).
             *
             *     * `F` - Femme
             *     * `H` - Homme
             */
            gender?: components["schemas"]["GenderEnum"] | components["schemas"]["BlankEnum"];
            /** @description Facultatif (statistiques). */
            birth_year?: number | null;
        };
        /** @description Vue plateforme : aucune donnée métier, uniquement l'identité du tenant. */
        PlatformOrganization: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug: string;
            type: components["schemas"]["TypeEnum"];
            readonly status: components["schemas"]["OrganizationStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Vue plateforme : aucune donnée métier, uniquement l'identité du tenant. */
        PlatformOrganizationRequest: {
            name: string;
            slug: string;
            type: components["schemas"]["TypeEnum"];
            /** Format: email */
            admin_email: string;
            admin_full_name: string;
        };
        Pme: {
            /** Format: uuid */
            readonly id: string;
            /** Raison sociale */
            legal_name: string;
            /** Sigle ou nom commercial */
            trade_name?: string;
            legal_form?: components["schemas"]["RefItem"] | null;
            /** N° RCCM */
            rccm_number?: string;
            /** N° de compte contribuable */
            ncc?: string;
            /** N° employeur CNPS */
            cnps_employer_number?: string;
            /** Format: date */
            creation_date?: string | null;
            sector?: components["schemas"]["RefItem"] | null;
            region?: components["schemas"]["RefItem"] | null;
            commune?: string;
            address?: string;
            phone?: string;
            email?: string;
            website?: string;
            /** Effectif déclaré */
            headcount?: number | null;
            size_category?: components["schemas"]["SizeCategoryEnum"];
            readonly lifecycle_status: components["schemas"]["LifecycleStatusEnum"];
            /** Format: date-time */
            readonly onboarding_started_at: string | null;
            /** Format: date-time */
            readonly exited_at: string | null;
            readonly exit_reason: components["schemas"]["ExitReasonEnum"];
            /** Format: date-time */
            readonly last_activity_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly principal_advisor: components["schemas"]["AdvisorSummary"] | null;
            readonly persons: components["schemas"]["Person"][];
            readonly assignments: components["schemas"]["Assignment"][];
            readonly enrollments: components["schemas"]["Enrollment"][];
        };
        PmeCreateRequest: {
            /** Raison sociale */
            legal_name: string;
            /** Sigle ou nom commercial */
            trade_name?: string;
            /** Format: uuid */
            legal_form?: string | null;
            /** N° RCCM */
            rccm_number?: string;
            /** N° de compte contribuable */
            ncc?: string;
            /** N° employeur CNPS */
            cnps_employer_number?: string;
            /** Format: date */
            creation_date?: string | null;
            /** Format: uuid */
            sector?: string | null;
            /** Format: uuid */
            region?: string | null;
            commune?: string;
            address?: string;
            phone?: string;
            email?: string;
            website?: string;
            /** Effectif déclaré */
            headcount?: number | null;
            size_category?: components["schemas"]["SizeCategoryEnum"];
            primary_person?: components["schemas"]["PersonRequest"];
            /** Format: uuid */
            advisor_id?: string | null;
            /** Format: uuid */
            cohort_id?: string | null;
            /** @default false */
            confirm_duplicates: boolean;
            /** @default false */
            start_onboarding: boolean;
        };
        PmeList: {
            /** Format: uuid */
            readonly id: string;
            /** Raison sociale */
            readonly legal_name: string;
            /** Sigle ou nom commercial */
            readonly trade_name: string;
            /** N° RCCM */
            readonly rccm_number: string;
            sector: components["schemas"]["RefItem"] | null;
            region: components["schemas"]["RefItem"] | null;
            readonly commune: string;
            readonly size_category: components["schemas"]["SizeCategoryEnum"];
            /** Effectif déclaré */
            readonly headcount: number | null;
            readonly lifecycle_status: components["schemas"]["LifecycleStatusEnum"];
            readonly principal_advisor: components["schemas"]["AdvisorSummary"] | null;
            /** Format: date-time */
            readonly last_activity_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `gude` - gude
         *     * `pme` - pme
         *     * `platform` - platform
         *     * `none` - none
         * @enum {string}
         */
        PortalEnum: "gude" | "pme" | "platform" | "none";
        Programme: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            funder?: string;
            objectives?: unknown;
            readonly cohorts: components["schemas"]["Cohort"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        ProgrammeRequest: {
            name: string;
            description?: string;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            funder?: string;
            objectives?: unknown;
        };
        /**
         * @description * `rccm` - rccm
         *     * `ncc` - ncc
         *     * `name` - name
         * @enum {string}
         */
        ReasonsEnum: "rccm" | "ncc" | "name";
        RefItem: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
        };
        Role: {
            /** Format: uuid */
            readonly id: string;
            code: string;
            label: string;
            default_scope: components["schemas"]["ScopeEnum"];
            /** @description Rôle côté PME (portail PME, connexion par OTP). */
            is_pme_role?: boolean;
            readonly permissions: string[];
        };
        /**
         * @description * `GERANT` - Gérant
         *     * `DG` - Directeur général
         *     * `PCA` - Président du conseil d'administration
         *     * `PRESIDENT` - Président
         *     * `ASSOCIE` - Associé
         *     * `DIRECTEUR` - Directeur
         *     * `CONTACT` - Contact
         * @enum {string}
         */
        RoleEnum: "GERANT" | "DG" | "PCA" | "PRESIDENT" | "ASSOCIE" | "DIRECTEUR" | "CONTACT";
        /**
         * @description * `CONSEILLER_PRINCIPAL` - Conseiller principal
         *     * `EXPERT` - Expert
         * @enum {string}
         */
        RoleInPmeEnum: "CONSEILLER_PRINCIPAL" | "EXPERT";
        /**
         * @description * `ORG` - Toute l'organisation
         *     * `PROGRAMME` - Un programme
         *     * `PORTEFEUILLE` - PME assignées
         *     * `PME` - Sa propre PME
         * @enum {string}
         */
        ScopeEnum: "ORG" | "PROGRAMME" | "PORTEFEUILLE" | "PME";
        /**
         * @description * `NON_DETERMINEE` - Non déterminée
         *     * `MICRO` - Micro-entreprise
         *     * `PETITE` - Petite entreprise
         *     * `MOYENNE` - Moyenne entreprise
         *     * `HORS_PME` - Hors PME
         * @enum {string}
         */
        SizeCategoryEnum: "NON_DETERMINEE" | "MICRO" | "PETITE" | "MOYENNE" | "HORS_PME";
        SwitchOrganizationRequest: {
            /** Format: uuid */
            organization_id: string;
        };
        TimelineEntry: {
            id: number;
            /** Format: date-time */
            at: string;
            action: string;
            label: string;
            actor: string | null;
            before: unknown;
            after: unknown;
        };
        TransitionRequest: {
            to: components["schemas"]["LifecycleStatusEnum"];
            /** @default  */
            reason: string;
            /** @default  */
            exit_reason: components["schemas"]["ExitReasonEnum"] | components["schemas"]["BlankEnum"];
        };
        /**
         * @description * `AGENCE_PUBLIQUE` - Agence ou programme public
         *     * `BANQUE` - Banque
         *     * `INCUBATEUR` - Incubateur
         *     * `ONG` - ONG
         *     * `BAILLEUR` - Bailleur
         *     * `CABINET` - Cabinet
         *     * `ASSOCIATION` - Association professionnelle
         * @enum {string}
         */
        TypeEnum: "AGENCE_PUBLIQUE" | "BANQUE" | "INCUBATEUR" | "ONG" | "BAILLEUR" | "CABINET" | "ASSOCIATION";
        UserSummary: {
            /** Format: uuid */
            readonly id: string;
            full_name: string;
            /** Format: email */
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_logs_list: {
        parameters: {
            query?: {
                action?: string;
                actor?: string;
                entity_id?: string;
                entity_type?: string;
                from?: string;
                pme_id?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLog"][];
                };
            };
        };
    };
    audit_logs_verify_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainVerification"];
                };
            };
        };
    };
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginStatus"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_mfa_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginStatus"];
                };
            };
        };
    };
    auth_mfa_setup_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaSetup"];
                };
            };
        };
    };
    auth_mfa_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginStatus"];
                };
            };
        };
    };
    auth_otp_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_otp_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginStatus"];
                };
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_switch_organization_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchOrganizationRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboards_advisor_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    dashboards_pme_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pme_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    dashboards_portfolio_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    memberships_revoke_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
        };
    };
    organization_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    organization_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOrganizationUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    platform_organizations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformOrganization"][];
                };
            };
        };
    };
    platform_organizations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformOrganizationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformOrganization"];
                };
            };
        };
    };
    pmes_list: {
        parameters: {
            query?: {
                /** @description « me » ou identifiant d'un conseiller */
                advisor?: string;
                /** @description La valeur du curseur de pagination. */
                cursor?: string;
                lifecycle_status?: string;
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                /** @description Nombre de résultats à retourner par page. */
                page_size?: number;
                /** @description Recherche : raison sociale, sigle, RCCM, NCC */
                q?: string;
                /** @description Code région */
                region?: string;
                /** @description Code secteur */
                sector?: string;
                size_category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPmeListList"];
                };
            };
        };
    };
    pmes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PmeCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pme"];
                };
            };
        };
    };
    pmes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pme"];
                };
            };
        };
    };
    pmes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPmeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pme"];
                };
            };
        };
    };
    pmes_assignments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    pmes_assignments_end_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    pmes_timeline_list: {
        parameters: {
            query?: {
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEntry"][];
                };
            };
        };
    };
    pmes_transition_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pme"];
                };
            };
        };
    };
    pmes_persons_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pme_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"][];
                };
            };
        };
    };
    pmes_persons_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pme_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
        };
    };
    pmes_persons_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                pme_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
        };
    };
    pmes_persons_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                pme_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pmes_persons_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                pme_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPersonRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Person"];
                };
            };
        };
    };
    pmes_duplicates_list: {
        parameters: {
            query?: {
                legal_name?: string;
                ncc?: string;
                /** @description Quel champ utiliser pour classer les résultats. */
                ordering?: string;
                rccm_number?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Duplicate"][];
                };
            };
        };
    };
    programmes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Programme"][];
                };
            };
        };
    };
    programmes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgrammeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Programme"];
                };
            };
        };
    };
    programmes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Programme"];
                };
            };
        };
    };
    programmes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProgrammeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Programme"];
                };
            };
        };
    };
    programmes_cohorts_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cohort"][];
                };
            };
        };
    };
    programmes_cohorts_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CohortRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cohort"][];
                };
            };
        };
    };
    ref_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefItem"][];
                };
            };
        };
    };
    roles_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationMember"][];
                };
            };
        };
    };
    users_advisors_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"][];
                };
            };
        };
    };
    users_invite_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
        };
    };
}
