# Generated by Django 5.2.17 on 2026-09-25 14:35

import django.db.models.deletion
import django.utils.timezone
import pme360.accounts.models
import pme360.core.fields
import pme360.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('full_name', models.CharField(max_length=200)),
                ('locale', models.CharField(default='fr', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_platform_admin', models.BooleanField(default=False)),
                ('mfa_secret', pme360.core.fields.EncryptedTextField(blank=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_last_timestep', models.BigIntegerField(blank=True, null=True)),
                ('failed_login_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_user',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', pme360.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'permission',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'role_permission',
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('ORG', "Toute l'organisation"), ('PROGRAMME', 'Un programme'), ('PORTEFEUILLE', 'PME assignées'), ('PME', 'Sa propre PME')], max_length=20)),
                ('scope_ref_id', models.UUIDField(blank=True, help_text='Programme ou PME selon le périmètre.', null=True)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_membership',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Connexion')], max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'one_time_code',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('default_scope', models.CharField(choices=[('ORG', "Toute l'organisation"), ('PROGRAMME', 'Un programme'), ('PORTEFEUILLE', 'PME assignées'), ('PME', 'Sa propre PME')], max_length=20)),
                ('is_pme_role', models.BooleanField(default=False, help_text='Rôle côté PME (portail PME, connexion par OTP).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role',
                'ordering': ['code'],
            },
        ),
    ]
