# Generated by Django 5.2.17 on 2026-09-26 14:18

import django.db.models.deletion
import pme360.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=pme360.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('ACTION', "Action du plan d'accompagnement")], max_length=12)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Active'), ('RETIRED', 'Retirée')], default='DRAFT', max_length=8)),
                ('states', models.JSONField(default=dict)),
                ('transitions', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_definition',
                'ordering': ['target_type', '-version'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'target_type', 'version'), name='workflow_definition_unique_version'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('organization', 'target_type'), name='workflow_one_active'), models.UniqueConstraint(condition=models.Q(('status', 'DRAFT')), fields=('organization', 'target_type'), name='workflow_one_draft')],
            },
        ),
    ]
